local Utils = require('_tools/utils')

local data = {
    ["ANCHOR_BOTTOM"] = {tips = "",val = "2"},
    ["ANCHOR_LEFT"] = {tips = "",val = "1"},
    ["ANCHOR_MIDDLE"] = {tips = "",val = "0"},
    ["ANCHOR_RIGHT"] = {tips = "",val = "2"},
    ["ANCHOR_TOP"] = {tips = "",val = "1"},
    
    ["CONTROL_ACCEPT"] = {tips = "",val = "29"},
    ["CONTROL_ACTION"] = {tips = "",val = "4"},
    ["CONTROL_ATTACK"] = {tips = "",val = "2"},
    ["CONTROL_CANCEL"] = {tips = "",val = "30"},
    ["CONTROL_CONTROLLER_ACTION"] = {tips = "",val = "57"},
    ["CONTROL_CONTROLLER_ALTACTION"] = {tips = "",val = "58"},
    ["CONTROL_CONTROLLER_ATTACK"] = {tips = "",val = "56"},
    ["CONTROL_CRAFTING_MODIFIER"] = {tips = "",val = "74"},
    ["CONTROL_CRAFTING_PINLEFT"] = {tips = "",val = "75"},
    ["CONTROL_CRAFTING_PINRIGHT"] = {tips = "",val = "76"},
    ["CONTROL_CUSTOM_START"] = {tips = "",val = "100"},
    ["CONTROL_FOCUS_DOWN"] = {tips = "",val = "26"},
    ["CONTROL_FOCUS_LEFT"] = {tips = "",val = "27"},
    ["CONTROL_FOCUS_RIGHT"] = {tips = "",val = "28"},
    ["CONTROL_FOCUS_UP"] = {tips = "",val = "25"},
    ["CONTROL_FORCE_ATTACK"] = {tips = "",val = "39"},
    ["CONTROL_FORCE_INSPECT"] = {tips = "",val = "38"},
    ["CONTROL_FORCE_STACK"] = {tips = "",val = "41"},
    ["CONTROL_FORCE_TRADE"] = {tips = "",val = "40"},
    ["CONTROL_INSPECT"] = {tips = "",val = "3"},
    ["CONTROL_INSPECT_SELF"] = {tips = "",val = "72"},
    ["CONTROL_INVENTORY_DOWN"] = {tips = "",val = "50"},
    ["CONTROL_INVENTORY_DROP"] = {tips = "",val = "54"},
    ["CONTROL_INVENTORY_EXAMINE"] = {tips = "",val = "51"},
    ["CONTROL_INVENTORY_LEFT"] = {tips = "",val = "47"},
    ["CONTROL_INVENTORY_RIGHT"] = {tips = "",val = "48"},
    ["CONTROL_INVENTORY_UP"] = {tips = "",val = "49"},
    ["CONTROL_INVENTORY_USEONSCENE"] = {tips = "",val = "53"},
    ["CONTROL_INVENTORY_USEONSELF"] = {tips = "",val = "52"},
    ["CONTROL_INV_1"] = {tips = "",val = "15"},
    ["CONTROL_INV_10"] = {tips = "",val = "24"},
    ["CONTROL_INV_11"] = {tips = "",val = "77"},
    ["CONTROL_INV_12"] = {tips = "",val = "78"},
    ["CONTROL_INV_13"] = {tips = "",val = "79"},
    ["CONTROL_INV_14"] = {tips = "",val = "80"},
    ["CONTROL_INV_15"] = {tips = "",val = "81"},
    ["CONTROL_INV_2"] = {tips = "",val = "16"},
    ["CONTROL_INV_3"] = {tips = "",val = "17"},
    ["CONTROL_INV_4"] = {tips = "",val = "18"},
    ["CONTROL_INV_5"] = {tips = "",val = "19"},
    ["CONTROL_INV_6"] = {tips = "",val = "20"},
    ["CONTROL_INV_7"] = {tips = "",val = "21"},
    ["CONTROL_INV_8"] = {tips = "",val = "22"},
    ["CONTROL_INV_9"] = {tips = "",val = "23"},
    ["CONTROL_MAP"] = {tips = "",val = "14"},
    ["CONTROL_MAP_ZOOM_IN"] = {tips = "",val = "60"},
    ["CONTROL_MAP_ZOOM_OUT"] = {tips = "",val = "61"},
    ["CONTROL_MENU_BACK"] = {tips = "",val = "83"},
    ["CONTROL_MENU_L2"] = {tips = "",val = "85"},
    ["CONTROL_MENU_MISC_1"] = {tips = "",val = "68"},
    ["CONTROL_MENU_MISC_2"] = {tips = "",val = "69"},
    ["CONTROL_MENU_MISC_3"] = {tips = "",val = "70"},
    ["CONTROL_MENU_MISC_4"] = {tips = "",val = "71"},
    ["CONTROL_MENU_R2"] = {tips = "",val = "86"},
    ["CONTROL_MENU_START"] = {tips = "",val = "84"},
    ["CONTROL_MOVE_DOWN"] = {tips = "",val = "6"},
    ["CONTROL_MOVE_LEFT"] = {tips = "",val = "7"},
    ["CONTROL_MOVE_RIGHT"] = {tips = "",val = "8"},
    ["CONTROL_MOVE_UP"] = {tips = "",val = "5"},
    ["CONTROL_NEXTVALUE"] = {tips = "",val = "34"},
    ["CONTROL_OPEN_COMMAND_WHEEL"] = {tips = "",val = "87"},
    ["CONTROL_OPEN_CRAFTING"] = {tips = "",val = "46"},
    ["CONTROL_OPEN_DEBUG_CONSOLE"] = {tips = "",val = "42"},
    ["CONTROL_OPEN_DEBUG_MENU"] = {tips = "",val = "70"},
    ["CONTROL_OPEN_INVENTORY"] = {tips = "",val = "45"},
    ["CONTROL_PAUSE"] = {tips = "",val = "13"},
    ["CONTROL_PREVVALUE"] = {tips = "",val = "33"},
    ["CONTROL_PRIMARY"] = {tips = "",val = "0"},
    ["CONTROL_PUTSTACK"] = {tips = "",val = "55"},
    ["CONTROL_ROTATE_LEFT"] = {tips = "",val = "11"},
    ["CONTROL_ROTATE_RIGHT"] = {tips = "",val = "12"},
    ["CONTROL_SCROLLBACK"] = {tips = "",val = "31"},
    ["CONTROL_SCROLLFWD"] = {tips = "",val = "32"},
    ["CONTROL_SECONDARY"] = {tips = "",val = "1"},
    ["CONTROL_SERVER_PAUSE"] = {tips = "",val = "73"},
    ["CONTROL_SHOW_PLAYER_STATUS"] = {tips = "",val = "67"},
    ["CONTROL_SPLITSTACK"] = {tips = "",val = "35"},
    ["CONTROL_START_EMOJI"] = {tips = "",val = "82"},
    ["CONTROL_TARGET_CYCLE"] = {tips = "",val = "89"},
    ["CONTROL_TARGET_CYCLE_BACK"] = {tips = "",val = "11"},
    ["CONTROL_TARGET_CYCLE_FORWARD"] = {tips = "",val = "12"},
    ["CONTROL_TARGET_LOCK"] = {tips = "",val = "69"},
    ["CONTROL_TARGET_MODIFIER"] = {tips = "",val = "69"},
    ["CONTROL_TOGGLE_DEBUGRENDER"] = {tips = "",val = "44"},
    ["CONTROL_TOGGLE_LOG"] = {tips = "",val = "43"},
    ["CONTROL_TOGGLE_PLAYER_STATUS"] = {tips = "",val = "66"},
    ["CONTROL_TOGGLE_SAY"] = {tips = "",val = "63"},
    ["CONTROL_TOGGLE_SLASH_COMMAND"] = {tips = "",val = "65"},
    ["CONTROL_TOGGLE_WHISPER"] = {tips = "",val = "64"},
    ["CONTROL_TRADEITEM"] = {tips = "",val = "36"},
    ["CONTROL_TRADESTACK"] = {tips = "",val = "37"},
    ["CONTROL_USE_ITEM_ON_ITEM"] = {tips = "",val = "59"},
    ["CONTROL_ZOOM_IN"] = {tips = "",val = "9"},
    ["CONTROL_ZOOM_OUT"] = {tips = "",val = "10"},
    ["FACING_DOWN"] = {tips = "",val = "3"},
    ["FACING_DOWNLEFT"] = {tips = "",val = "7"},
    ["FACING_DOWNRIGHT"] = {tips = "",val = "6"},
    ["FACING_LEFT"] = {tips = "",val = "2"},
    ["FACING_NONE"] = {tips = "",val = "8"},
    ["FACING_RIGHT"] = {tips = "",val = "0"},
    ["FACING_UP"] = {tips = "",val = "1"},
    ["FACING_UPLEFT"] = {tips = "",val = "5"},
    ["FACING_UPRIGHT"] = {tips = "",val = "4"},
    ["FACING_DOWN"] = {tips = "",val = "3"},
    ["FACING_DOWNLEFT"] = {tips = "",val = "7"},
    ["FACING_DOWNRIGHT"] = {tips = "",val = "6"},
    ["FACING_LEFT"] = {tips = "",val = "2"},
    ["FACING_NONE"] = {tips = "",val = "8"},
    ["FACING_RIGHT"] = {tips = "",val = "0"},
    ["FACING_UP"] = {tips = "",val = "1"},
    ["FACING_UPLEFT"] = {tips = "",val = "5"},
    ["FACING_UPRIGHT"] = {tips = "",val = "4"},
    ["MOUSEBUTTON_LEFT"] = {tips = "",val = "1000"},
    ["MOUSEBUTTON_MIDDLE"] = {tips = "",val = "1002"},
    ["MOUSEBUTTON_RIGHT"] = {tips = "",val = "1001"},
    ["MOUSEBUTTON_SCROLLDOWN"] = {tips = "",val = "1004"},
    ["MOUSEBUTTON_SCROLLUP"] = {tips = "",val = "1003"},
    ["MOVE_DOWN"] = {tips = "",val = "2"},
    ["MOVE_LEFT"] = {tips = "",val = "3"},
    ["MOVE_RIGHT"] = {tips = "",val = "4"},
    ["MOVE_UP"] = {tips = "",val = "1"},
    SCALEMODE_NONE = {tips = "",val = "0"},
    SCALEMODE_FILLSCREEN = {tips = "stretch art to fit/fill window",val = "1"}, --
    SCALEMODE_PROPORTIONAL = {tips = "preserve aspect ratio (picks the smaller of horizontal/vertical scale)",val = "2"}, --
    SCALEMODE_FIXEDPROPORTIONAL = {tips = "same as SCALEMODE_FIXEDSCREEN_NONDYNAMIC, except for safe area on consoles",val = "3"}, --
    SCALEMODE_FIXEDSCREEN_NONDYNAMIC = {tips = "scale same amount as window scaling from 1280x720",val = "4"}, --
    EQUIPSLOTS = {tips = "",val = "表"},
    ["EQUIPSLOTS.HANDS"]= {tips = "",val = "hands"},
    ["EQUIPSLOTS.HEAD"]= {tips = "",val = "head"},
    ["EQUIPSLOTS.BODY"]= {tips = "",val = "body"},
    ["EQUIPSLOTS.BEARD"]= {tips = "",val = "beard"},
    ITEMTAG = {tips = "",val = "表"},
    ["ITEMTAG.FOOD"]= {tips = "",val = "food"},
    ["ITEMTAG.MEAT"]= {tips = "",val = "meat"},
    ["ITEMTAG.WEAPON"]= {tips = "",val = "weapon"},
    ["ITEMTAG.TOOL"]= {tips = "",val = "tool"},
    ["ITEMTAG.TREASURE"]= {tips = "",val = "treasure"},
    ["ITEMTAG.FUEL"]= {tips = "",val = "fuel"},
    ["ITEMTAG.FIRE"]= {tips = "",val = "fire"},
    ["ITEMTAG.STACKABLE"]= {tips = "",val = "stackable"},
    ["ITEMTAG.FX"]= {tips = "",val = "FX"},
    OCEAN_DEPTH = {tips = "",val = '表'},
    ["OCEAN_DEPTH.SHALLOW"]= {tips = "",val = 1},
    ["OCEAN_DEPTH.NORMAL"]= {tips = "",val = 2},
    ["OCEAN_DEPTH.DEEP"]= {tips = "",val = 3},
    ["OCEAN_DEPTH.VERY_DEEP"]= {tips = "",val = 4},
    GROUND = {tips = "",val = "表"},
    ["GROUND.INVALID"]= {tips = "",val = 65535},
    ["GROUND.IMPASSABLE"]= {tips = "",val = 1},
    ["GROUND.ROAD"]= {tips = "",val = 2},
    ["GROUND.ROCKY"]= {tips = "",val = 3},
    ["GROUND.DIRT"]= {tips = "",val = 4},
    ["GROUND.SAVANNA"]= {tips = "",val = 5},
    ["GROUND.GRASS"]= {tips = "",val = 6},
    ["GROUND.FOREST"]= {tips = "",val = 7},
    ["GROUND.MARSH"]= {tips = "",val = 8},
    ["GROUND.WEB"]= {tips = "",val = 9},
    ["GROUND.WOODFLOOR"]= {tips = "",val = 10},
    ["GROUND.CARPET"]= {tips = "",val = 11},
    ["GROUND.CHECKER"]= {tips = "",val = 12},
    ["GROUND.CAVE"]= {tips = "",val = 13},
    ["GROUND.FUNGUS"]= {tips = "",val = 14},
    ["GROUND.SINKHOLE"]= {tips = "",val = 15},
    ["GROUND.UNDERROCK"]= {tips = "",val = 16},
    ["GROUND.MUD"]= {tips = "",val = 17},
    ["GROUND.BRICK"]= {tips = "",val = 18},
    ["GROUND.BRICK_GLOW"]= {tips = "",val = 19},
    ["GROUND.TILES"]= {tips = "",val = 20},
    ["GROUND.TILES_GLOW"]= {tips = "",val = 21},
    ["GROUND.TRIM"]= {tips = "",val = 22},
    ["GROUND.TRIM_GLOW"]= {tips = "",val = 23},
    ["GROUND.FUNGUSRED"]= {tips = "",val = 24},
    ["GROUND.FUNGUSGREEN"]= {tips = "",val = 25},
    ["GROUND.DECIDUOUS"]= {tips = "",val = 30},
    ["GROUND.DESERT_DIRT"]= {tips = "",val = 31},
    ["GROUND.SCALE"]= {tips = "",val = 32},
    ["GROUND.LAVAARENA_FLOOR"]= {tips = "",val = 33},
    ["GROUND.LAVAARENA_TRIM"]= {tips = "",val = 34},
    ["GROUND.QUAGMIRE_PEATFOREST"]= {tips = "",val = 35},
    ["GROUND.QUAGMIRE_PARKFIELD"]= {tips = "",val = 36},
    ["GROUND.QUAGMIRE_PARKSTONE"]= {tips = "",val = 37},
    ["GROUND.QUAGMIRE_GATEWAY"]= {tips = "",val = 38},
    ["GROUND.QUAGMIRE_SOIL"]= {tips = "",val = 39},
    ["GROUND.QUAGMIRE_CITYSTONE"]= {tips = "",val = 41},
    ["GROUND.PEBBLEBEACH"]= {tips = "",val = 42},
    ["GROUND.METEOR"]= {tips = "",val = 43},
    ["GROUND.SHELLBEACH"]= {tips = "",val = 44},
    ["GROUND.ARCHIVE"]= {tips = "",val = 45},
    ["GROUND.FUNGUSMOON"]= {tips = "",val = 46},
    ["GROUND.FARMING_SOIL"]= {tips = "",val = 47},
    ["GROUND.FUNGUSMOON_NOISE"]= {tips = "",val = 120},
    ["GROUND.METEORMINE_NOISE"]= {tips = "",val = 121},
    ["GROUND.METEORCOAST_NOISE"]= {tips = "",val = 122},
    ["GROUND.DIRT_NOISE"]= {tips = "",val = 123},
    ["GROUND.ABYSS_NOISE"]= {tips = "",val = 124},
    ["GROUND.GROUND_NOISE"]= {tips = "",val = 125},
    ["GROUND.CAVE_NOISE"]= {tips = "",val = 126},
    ["GROUND.FUNGUS_NOISE"]= {tips = "",val = 127},
    ["GROUND.UNDERGROUND"]= {tips = "",val = 128},
    ["GROUND.WALL_ROCKY"]= {tips = "",val = 151},
    ["GROUND.WALL_DIRT"]= {tips = "",val = 152},
    ["GROUND.WALL_MARSH"]= {tips = "",val = 153},
    ["GROUND.WALL_CAVE"]= {tips = "",val = 154},
    ["GROUND.WALL_FUNGUS"]= {tips = "",val = 155},
    ["GROUND.WALL_SINKHOLE"]= {tips = "",val = 156},
    ["GROUND.WALL_MUD"]= {tips = "",val = 157},
    ["GROUND.WALL_TOP"]= {tips = "",val = 158},
    ["GROUND.WALL_WOOD"]= {tips = "",val = 159},
    ["GROUND.WALL_HUNESTONE"]= {tips = "",val = 160},
    ["GROUND.WALL_HUNESTONE_GLOW"]= {tips = "",val = 161},
    ["GROUND.WALL_STONEEYE"]= {tips = "",val = 162},
    ["GROUND.WALL_STONEEYE_GLOW"]= {tips = "",val = 163},
    ["GROUND.FAKE_GROUND"]= {tips = "",val = 200},
    ["GROUND.OCEAN_START"]= {tips = "",val = 201},
    ["GROUND.OCEAN_COASTAL"]= {tips = "",val = 201},
    ["GROUND.OCEAN_COASTAL_SHORE"]= {tips = "",val = 202},
    ["GROUND.OCEAN_SWELL"]= {tips = "",val = 203},
    ["GROUND.OCEAN_ROUGH"]= {tips = "",val = 204},
    ["GROUND.OCEAN_BRINEPOOL"]= {tips = "",val = 205},
    ["GROUND.OCEAN_BRINEPOOL_SHORE"]= {tips = "",val = 206},
    ["GROUND.OCEAN_HAZARDOUS"]= {tips = "",val = 207},
    ["GROUND.OCEAN_WATERLOG"]= {tips = "",val = 208},
    ["GROUND.OCEAN_END"]= {tips = "",val = 247},
    TECH = {tips = "",val = "表"},
    ["TECH.NONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SCIENCE_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SCIENCE_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SCIENCE_THREE"] = {tips = "",val = "UNKNOWN"},
    -- Magic starts at level 2 so it's not teased from the start.
    ["TECH.MAGIC_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.MAGIC_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.ANCIENT_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.ANCIENT_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.ANCIENT_FOUR"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CELESTIAL_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CELESTIAL_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.MOON_ALTAR_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SHADOW_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CARTOGRAPHY_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SEAFARING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SEAFARING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SCULPTING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SCULPTING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.ORPHANAGE_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.PERDOFFERING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.PERDOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.WARGOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.PIGOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CARRATOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.BEEFOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CATCOONOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.RABBITOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.DRAGONOFFERING_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.MADSCIENCE_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CARNIVAL_PRIZESHOP_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CARNIVAL_HOSTSHOP_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CARNIVAL_HOSTSHOP_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.FOODPROCESSING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.FISHING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.FISHING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.HERMITCRABSHOP_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.HERMITCRABSHOP_THREE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.HERMITCRABSHOP_FIVE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.HERMITCRABSHOP_SEVEN"] = {tips = "",val = "UNKNOWN"},
    ["TECH.TURFCRAFTING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.TURFCRAFTING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.MASHTURFCRAFTING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.WINTERSFEASTCOOKING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.HALLOWED_NIGHTS"] = {tips = "",val = "UNKNOWN"},
    ["TECH.WINTERS_FEAST"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTG"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTV"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTP"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTC"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTB"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOT_CATCOON"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTR"] = {tips = "",val = "UNKNOWN"},
    ["TECH.YOTD"] = {tips = "",val = "UNKNOWN"},
    ["TECH.LOST"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SPIDERCRAFT_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.ROBOTMODULECRAFT_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.BOOKCRAFT_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.LUNARFORGING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.LUNARFORGING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SHADOWFORGING_ONE"] = {tips = "",val = "UNKNOWN"},
    ["TECH.SHADOWFORGING_TWO"] = {tips = "",val = "UNKNOWN"},
    ["TECH.CARPENTRY_TWO"] = {tips = "",val = "UNKNOWN"},
    NODE_TYPE = {tips = "",val = "表"},
    ["NODE_TYPE.Default"] = {tips = "Land can touch any other Default node in the task that is within range",val = "0"},		-- 
    ["NODE_TYPE.Blank"] = {tips = "empty room with impassable ground",val = "1"},			-- 
    ["NODE_TYPE.Background"] = {tips = "",val = "2"},
    ["NODE_TYPE.Random"] = {tips = "",val = "3"},
    ["NODE_TYPE.Blocker"] = {tips = "Adds 2 Blank nodes beside it",val = "4"},		-- 
    ["NODE_TYPE.Room"] = {tips = "Land can only touch the room(s) it is connected to by the graph (adds impassable around its parameter with a single land bidge)",val = "5"},			-- 
    ["NODE_TYPE.BackgroundRoom"] = {tips = "",val = "6"},
    ["NODE_TYPE.SeparatedRoom"] = {tips = "adds impassable around its entire parameter",val = "7"},	-- 
    ["COLLISION"] = {tips = "keep up to date with COLLISION_GROUP in simconstants.h",val = "32"},
["COLLISION.GROUND"] = {tips = "",val = "32"},
["COLLISION.BOAT_LIMITS"] = {tips = "",val = "64"},
["COLLISION.LAND_OCEAN_LIMITS"] = {tips = "physics wall between water and land",val = "128"},
["COLLISION.LIMITS"] = {tips = "BOAT_LIMITS + LAND_OCEAN_LIMITS",val = "128 + 64"},
["COLLISION.WORLD"] = {tips = "BOAT_LIMITS + LAND_OCEAN_LIMITS + GROUND",val = "128 + 64 + 32"},
["COLLISION.ITEMS"] = {tips = "",val = "256"},
["COLLISION.OBSTACLES"] = {tips = "",val = "512"},
["COLLISION.CHARACTERS"] = {tips = "",val = "1024"},
["COLLISION.FLYERS"] = {tips = "",val = "2048"},
["COLLISION.SANITY"] = {tips = "",val = "4096"},
["COLLISION.SMALLOBSTACLES"] = {tips = "collide with characters but not giants",val = "8192"},
["COLLISION.GIANTS"] = {tips = "collide with obstacles but not small obstacles",val = "16384"},

["BLENDMODE"] = {tips = "",val = "表"},
["BLENDMODE.Disabled"] = {tips = "",val = "0"},
["BLENDMODE.AlphaBlended"] = {tips = "",val = "1"},
["BLENDMODE.Additive"] = {tips = "",val = "2"},
["BLENDMODE.Premultiplied"] = {tips = "",val = "3"},
["BLENDMODE.InverseAlpha"] = {tips = "",val = "4"},
["BLENDMODE.AlphaAdditive"] = {tips = "",val = "5"},
["BLENDMODE.VFXTest"] = {tips = "",val = "6"},
["ANIM_ORIENTATION"] = {tips = "",val = "表"},
["ANIM_ORIENTATION.BillBoard"] = {tips = "",val = "0"},
["ANIM_ORIENTATION.OnGround"] = {tips = "",val = "1"},
["ANIM_ORIENTATION.OnGroundFixed"] = {tips = "",val = "2"},
["ANIM_SORT_ORDER"] = {tips = "",val = "表"},
["ANIM_SORT_ORDER.OCEAN_UNDERWATER"] = {tips = "",val = "0"},
["ANIM_SORT_ORDER.OCEAN_WAVES"] = {tips = "",val = "1"},
["ANIM_SORT_ORDER.OCEAN_WHIRLPORTAL"] = {tips = "",val = "1"},
["ANIM_SORT_ORDER.OCEAN_BOAT"] = {tips = "Keep at 2.",val = "2"},
["ANIM_SORT_ORDER.OCEAN_BOAT_BUMPERS"] = {tips = "",val = "3"},
["ANIM_SORT_ORDER.OCEAN_SKYSHADOWS"] = {tips = "",val = "4"},
["ANIM_SORT_ORDER_BELOW_GROUND"] = {tips = "",val = "表"},
["ANIM_SORT_ORDER_BELOW_GROUND.UNDERWATER"] = {tips = "",val = "0"},
["ANIM_SORT_ORDER_BELOW_GROUND.BOAT_TRAIL"] = {tips = "",val = "1"},
["ANIM_SORT_ORDER_BELOW_GROUND.BOAT_LIP"] = {tips = "",val = "2"},
["ANIM_SORT_ORDER_BELOW_GROUND.UNUSED"] = {tips = "",val = "3"},
["ROAD_PARAMETERS"] = {tips = "",val = "表"},
["ROAD_PARAMETERS.NUM_SUBDIVISIONS_PER_SEGMENT"] = {tips = "",val = "50"},
["ROAD_PARAMETERS.MIN_WIDTH"] = {tips = "",val = "2"},
["ROAD_PARAMETERS.MAX_WIDTH"] = {tips = "",val = "3"},
["ROAD_PARAMETERS.MIN_EDGE_WIDTH"] = {tips = "",val = "0.5"},
["ROAD_PARAMETERS.MAX_EDGE_WIDTH"] = {tips = "",val = "1"},
["BGCOLOURS"] = {tips = "",val = "表"},
["BGCOLOURS.RED"] = {tips = "",val = "RGB(255, 89,  46 )"},
["BGCOLOURS.PURPLE"] = {tips = "",val = "RGB(184, 87,  198)"},
["BGCOLOURS.YELLOW"] = {tips = "",val = "RGB(255, 196, 45 )"},
["BGCOLOURS.GREY"] = {tips = "",val = "RGB(75,  75,  75 )"},
["BGCOLOURS.HALF"] = {tips = "",val = "RGB(128, 128, 128 )"},
["BGCOLOURS.FULL"] = {tips = "",val = "RGB(255, 255, 255)"},
["WEBCOLOURS"] = { tips = "Standard html colours: https://en.wikipedia.org/wiki/Web_colors#X11_color_names", val = "表" },
["WEBCOLOURS.PINK"] = {tips = "",val = "RGB(255, 192, 203)"},
["WEBCOLOURS.PALEVIOLETRED"] = {tips = "",val = "RGB(219, 112, 147)"},
["WEBCOLOURS.SALMON"] = {tips = "",val = "RGB(250, 128, 114)"},
["WEBCOLOURS.CRIMSON"] = {tips = "",val = "RGB(220, 20, 60)"},
["WEBCOLOURS.FIREBRICK"] = {tips = "",val = "RGB(178, 34, 34)"},
["WEBCOLOURS.DARKRED"] = {tips = "",val = "RGB(139, 0, 0)"},
["WEBCOLOURS.RED"] = {tips = "",val = "RGB(255, 0, 0)"},
["WEBCOLOURS.TOMATO"] = {tips = "",val = "RGB(255, 99, 71)"},
["WEBCOLOURS.CORAL"] = {tips = "",val = "RGB(255, 127, 80)"},
["WEBCOLOURS.ORANGE"] = {tips = "",val = "RGB(255, 165, 0)"},
["WEBCOLOURS.YELLOW"] = {tips = "",val = "RGB(255, 255, 0)"},
["WEBCOLOURS.KHAKI"] = {tips = "",val = "RGB(240, 230, 140)"},
["WEBCOLOURS.BISQUE"] = {tips = "",val = "RGB(255, 228, 196)"},
["WEBCOLOURS.BURLYWOOD"] = {tips = "",val = "RGB(222, 184, 135)"},
["WEBCOLOURS.TAN"] = {tips = "",val = "RGB(210, 180, 140)"},
["WEBCOLOURS.ROSYBROWN"] = {tips = "",val = "RGB(188, 143, 143)"},
["WEBCOLOURS.SANDYBROWN"] = {tips = "",val = "RGB(244, 164, 96)"},
["WEBCOLOURS.GOLDENROD"] = {tips = "",val = "RGB(218, 165, 32)"},
["WEBCOLOURS.PERU"] = {tips = "",val = "RGB(205, 133, 63)"},
["WEBCOLOURS.CHOCOLATE"] = {tips = "",val = "RGB(210, 105, 30)"},
["WEBCOLOURS.SADDLEBROWN"] = {tips = "",val = "RGB(139, 69, 19)"},
["WEBCOLOURS.BROWN"] = {tips = "",val = "RGB(165, 42, 42)"},
["WEBCOLOURS.GREEN"] = {tips = "",val = "RGB(0, 128, 0)"},
["WEBCOLOURS.SPRINGGREEN"] = {tips = "",val = "RGB( 0, 255, 127)"},
["WEBCOLOURS.TURQUOISE"] = {tips = "",val = "RGB(64, 224, 208)"},
["WEBCOLOURS.TEAL"] = {tips = "",val = "RGB(0, 128, 128)"},
["WEBCOLOURS.LIGHTSKYBLUE"] = {tips = "",val = "RGB(135, 206, 250)"},
["WEBCOLOURS.CORNFLOWERBLUE"] = {tips = "",val = "RGB(100, 149, 237)"},
["WEBCOLOURS.BLUE"] = {tips = "",val = "RGB(0, 0, 255)"},
["WEBCOLOURS.LAVENDER"] = {tips = "",val = "RGB(230, 230, 250)"},
["WEBCOLOURS.THISTLE"] = {tips = "",val = "RGB(216, 191, 216)"},
["WEBCOLOURS.PLUM"] = {tips = "",val = "RGB(221, 160, 221)"},
["WEBCOLOURS.MEDIUMPURPLE"] = {tips = "",val = "RGB(147, 112, 219)"},
["WEBCOLOURS.PURPLE"] = {tips = "",val = "RGB(128, 0, 128)"},
["MATERIALS"] = { tips = "Extended for DST", val = "表" },
["MATERIALS.WOOD"] = {tips = "",val = "wood"},
["MATERIALS.STONE"] = {tips = "",val = "stone"},
["MATERIALS.HAY"] = {tips = "",val = "hay"},
["MATERIALS.THULECITE"] = {tips = "",val = "thulecite"},
["MATERIALS.GEM"] = {tips = "",val = "gem"},
["MATERIALS.GEARS"] = {tips = "",val = "gears"},
["MATERIALS.MOONROCK"] = {tips = "",val = "moonrock"},
["MATERIALS.ICE"] = {tips = "",val = "ice"},
["MATERIALS.SCULPTURE"] = {tips = "",val = "sculpture"},
["MATERIALS.FOSSIL"] = {tips = "",val = "fossil"},
["MATERIALS.MOON_ALTAR"] = {tips = "",val = "moon_altar"},
["MATERIALS.KELP"] = {tips = "",val = "kelp"},
["MATERIALS.SHELL"] = {tips = "",val = "shell"},
["MATERIALS.NIGHTMARE"] = {tips = "",val = "nightmare"},
["MATERIALS.DREADSTONE"] = {tips = "",val = "dreadstone"},
["MATERIALS.SALT"] = {tips = "",val = "salt"},
["MATERIALS.VITAE"] = {tips = "",val = "vitae"},
["UICOLOURS"] = { tips = "A coherent palette for UI elements", val = "表" },
["UICOLOURS.GOLD_CLICKABLE"] = {tips = "interactive text & menu",val = "RGB(215, 210, 157)"},
["UICOLOURS.GOLD_FOCUS"] = {tips = "menu active item",val = "RGB(251, 193, 92)"},
["UICOLOURS.GOLD_SELECTED"] = {tips = "titles and non-interactive important text",val = "RGB(245, 243, 222)"},
["UICOLOURS.GOLD_UNIMPORTANT"] = {tips = "non-interactive non-important text",val = "RGB(213, 213, 203)"},
["UICOLOURS.HIGHLIGHT_GOLD"] = {tips = "",val = "RGB(243, 217, 161)"},
["UICOLOURS.GOLD"] = {tips = "",val = "GOLD"},
["UICOLOURS.BROWN_MEDIUM"] = {tips = "",val = "RGB(107, 84, 58)"},
["UICOLOURS.BROWN_DARK"] = {tips = "",val = "RGB(80, 61, 39)"},
["UICOLOURS.BLUE"] = {tips = "",val = "RGB(80, 143, 244)"},
["UICOLOURS.GREY"] = {tips = "",val = "GREY"},
["UICOLOURS.BLACK"] = {tips = "",val = "BLACK"},
["UICOLOURS.WHITE"] = {tips = "",val = "WHITE"},
["UICOLOURS.BRONZE"] = {tips = "",val = "RGB(180, 116, 36, 1)"},
["UICOLOURS.EGGSHELL"] = {tips = "",val = "RGB(252, 230, 201)"},
["UICOLOURS.IVORY"] = {tips = "",val = "RGB(236, 232, 223, 1)"},
["UICOLOURS.IVORY_70"] = {tips = "",val = "RGB(165, 162, 156, 1)"},
["UICOLOURS.PURPLE"] = {tips = "",val = "RGB(152, 86, 232, 1)"},
["UICOLOURS.RED"] = {tips = "",val = "RGB(207, 61, 61, 1)"},
["UICOLOURS.SLATE"] = {tips = "",val = "RGB(155, 170, 177, 1)"},
["UICOLOURS.SILVER"] = {tips = "",val = "RGB(192, 192, 192, 1)"},
["CAMERASHAKE"] = { tips = "Camera shake modes", val = "表" },
["CAMERASHAKE.FULL"] = {tips = "",val = "0"},
["CAMERASHAKE.SIDE"] = {tips = "",val = "1"},
["CAMERASHAKE.VERTICAL"] = {tips = "",val = "2"},
["RATE_SCALE"] = { tips = "Badge/meter arrow sizes", val = "表" },
["RATE_SCALE.NEUTRAL"] = {tips = "",val = "0"},
["RATE_SCALE.INCREASE_HIGH"] = {tips = "",val = "1"},
["RATE_SCALE.INCREASE_MED"] = {tips = "",val = "2"},
["RATE_SCALE.INCREASE_LOW"] = {tips = "",val = "3"},
["RATE_SCALE.DECREASE_HIGH"] = {tips = "",val = "4"},
["RATE_SCALE.DECREASE_MED"] = {tips = "",val = "5"},
["RATE_SCALE.DECREASE_LOW"] = {tips = "",val = "6"},
["ORDERS"] = { tips = "TeamAttacker orders", val = "表" },
["ORDERS.NONE"] = {tips = "",val = "0"},
["ORDERS.HOLD"] = {tips = "",val = "1"},
["ORDERS.WARN"] = {tips = "",val = "2"},
["ORDERS.ATTACK"] = {tips = "",val = "3"},
["PLAYERSTUNLOCK"] = { tips = "How does this creature apply stunlock to the player", val = "表" },
["PLAYERSTUNLOCK.ALWAYS"] = {tips = "",val = "nil,--0"},
["PLAYERSTUNLOCK.OFTEN"] = {tips = "",val = "1"},
["PLAYERSTUNLOCK.SOMETIMES"] = {tips = "",val = "2"},
["PLAYERSTUNLOCK.RARELY"] = {tips = "",val = "3"},
["PLAYERSTUNLOCK.NEVER"] = {tips = "",val = "4"},
["WORMHOLETYPE"] = { tips = "Which wormhole", val = "表" },
["WORMHOLETYPE.WORM"] = {tips = "",val = "0"},
["WORMHOLETYPE.TENTAPILLAR"] = {tips = "",val = "1"},
["WORMHOLETYPE.OCEANWHIRLPORTAL"] = {tips = "",val = "2"},
["HOUNDWARNINGTYPE"] = { tips = "Houndwarning level", val = "表" },
["HOUNDWARNINGTYPE.LVL1"] = {tips = "",val = "0"},
["HOUNDWARNINGTYPE.LVL2"] = {tips = "",val = "1"},
["HOUNDWARNINGTYPE.LVL3"] = {tips = "",val = "2"},
["HOUNDWARNINGTYPE.LVL4"] = {tips = "",val = "3"},
["HOUNDWARNINGTYPE.LVL1_WORM"] = {tips = "",val = "4"},
["HOUNDWARNINGTYPE.LVL2_WORM"] = {tips = "",val = "5"},
["HOUNDWARNINGTYPE.LVL3_WORM"] = {tips = "",val = "6"},
["HOUNDWARNINGTYPE.LVL4_WORM"] = {tips = "",val = "7"},
["TENDENCY"] = { tips = "驯化趋势", val = "表" },
["TENDENCY.DEFAULT"] = {tips = "",val = "DEFAULT"},
["TENDENCY.ORNERY"] = {tips = "",val = "ORNERY"},
["TENDENCY.RIDER"] = {tips = "",val = "RIDER"},
["TENDENCY.PUDGY"] = {tips = "",val = "PUDGY"},
["LEVELTYPE"] = { tips = "UNKNOWN", val = "表" },
["LEVELTYPE.SURVIVAL"] = {tips = "",val = "SURVIVAL"},
["LEVELTYPE.CAVE"] = {tips = "",val = "CAVE"},
["LEVELTYPE.ADVENTURE"] = {tips = "",val = "ADVENTURE"},
["LEVELTYPE.LAVAARENA"] = {tips = "",val = "LAVAARENA"},
["LEVELTYPE.QUAGMIRE"] = {tips = "",val = "QUAGMIRE"},
["LEVELTYPE.TEST"] = {tips = "",val = "TEST"},
["LEVELTYPE.UNKNOWN"] = {tips = "",val = "UNKNOWN"},
["LEVELTYPE.CUSTOM"] = {tips = "",val = "CUSTOM"},
["LEVELTYPE.CUSTOMPRESET"] = {tips = "",val = "CUSTOMPRESET"},

}

local res = {}
for k,v in pairs(data) do
    local res_tips = v.tips ~= nil and v.tips ~= "" and v.tips or "UNKNOWN"
    res[k] = {
        tips = tostring(res_tips),
        author = "lan (值为: "..tostring(v.val)..")",
    }
end

Utils:mergeSeveral('scripts','constant',res)
Utils:sortTbl2stringAndSave('constant','scripts')