-- 事件 , params是 pushevent 时 传递的 data 的参数
return {
    ["CHEVO_fertilized"] = {params = {}, tips = "", author = ""},
    ["CHEVO_growfrombutterfly"] = {params = {}, tips = "", author = ""},
    ["CHEVO_heavyobject_winched"] = {params = {}, tips = "", author = ""},
    ["CHEVO_lureplantdied"] = {params = {}, tips = "", author = ""},
    ["CHEVO_makechair"] = {params = {}, tips = "", author = ""},
    ["CHEVO_seastack_mined"] = {params = {}, tips = "", author = ""},
    ["CHEVO_starteddrying"] = {params = {}, tips = "", author = ""},
    ["LearnBuilderRecipe"] = {params = {}, tips = "", author = ""},
    ["MaxwellThreat"] = {params = {}, tips = "", author = ""},
    ["SetUpSpringSmallBird"] = {params = {}, tips = "", author = ""},
    ["abandon_ship"] = {params = {}, tips = "", author = ""},
    ["acidleveldelta"] = {params = {}, tips = "", author = ""},
    ["acidsizzlingchange"] = {params = {}, tips = "", author = ""},
    ["acting"] = {params = {}, tips = "", author = ""},
    ["actionfailed"] = {params = {}, tips = "", author = ""},
    ["activate"] = {params = {}, tips = "", author = ""},
    ["activated"] = {params = {}, tips = "", author = ""},
    ["activateresurrection"] = {params = {}, tips = "", author = ""},
    ["activewakeup"] = {params = {}, tips = "", author = ""},
    ["addfuel"] = {params = {}, tips = "", author = ""},
    ["aimingcannonchanged"] = {params = {}, tips = "", author = ""},
    ["ammoloaded"] = {params = {}, tips = "", author = ""},
    ["ammounloaded"] = {params = {}, tips = "", author = ""},
    ["anchor_lowered"] = {params = {}, tips = "", author = ""},
    ["anchor_raised"] = {params = {}, tips = "", author = ""},
    ["animover"] = {params = {}, tips = "", author = ""},
    ["animqueueover"] = {params = {}, tips = "", author = ""},
    ["antlion_leaveworld"] = {params = {}, tips = "", author = ""},
    ["antlionstopfighting"] = {params = {}, tips = "", author = ""},
    ["arhivepoweroff"] = {params = {}, tips = "", author = ""},
    ["arhivepoweron"] = {params = {}, tips = "", author = ""},
    ["armorbroke"] = {params = {}, tips = "", author = ""},
    ["armordamaged"] = {params = {}, tips = "", author = ""},
    ["arrive"] = {params = {}, tips = "", author = ""},
    ["atriumpowered"] = {params = {}, tips = "", author = ""},
    ["attackdodged"] = {params = {}, tips = "", author = ""},
    ["attacked"] = {params = {
        {param = "attacker", type = "", explain = "攻击者"},
        {param = "damage", type = "", explain = "伤害"},
        {param = "damageresolved", type = "", explain = ""},
        {param = "original_damage", type = "", explain = ""},
        {param = "weapon", type = "", explain = "使用的武器"},
        {param = "stimuli", type = "", explain = ""},
        {param = "spdamage", type = "", explain = ""},
        {param = "redirected", type = "", explain = ""},
        {param = "noimpactsound", type = "", explain = ""},
    }, tips = "combat组件中,挨打时推送", author = "lan"},
    ["attackedbygrue"] = {params = {}, tips = "", author = ""},
    ["attackstart"] = {params = {}, tips = "", author = ""},
    ["attuned"] = {params = {}, tips = "", author = ""},
    ["attunedresurrector"] = {params = {}, tips = "", author = ""},
    ["attunementlost"] = {params = {}, tips = "", author = ""},
    ["axepossessedbyplayer"] = {params = {}, tips = "", author = ""},
    ["axerejectedotheraxe"] = {params = {}, tips = "", author = ""},
    ["axerejectedowner"] = {params = {}, tips = "", author = ""},
    ["barnacle_grown"] = {params = {}, tips = "", author = ""},
    ["beacon_reached_checkpoint"] = {params = {}, tips = "", author = ""},
    ["beargerkilled"] = {params = {}, tips = "", author = ""},
    ["beargerremoved"] = {params = {}, tips = "", author = ""},
    ["beavernessdelta"] = {params = {}, tips = "", author = ""},
    ["becomeolder_wanda"] = {params = {}, tips = "", author = ""},
    ["becomestatue"] = {params = {}, tips = "", author = ""},
    ["becomeunsittable"] = {params = {}, tips = "", author = ""},
    ["becomeyounger_wanda"] = {params = {}, tips = "", author = ""},
    ["beefalo.domestication.brushed"] = {params = {}, tips = "", author = ""},
    ["beefalo.domestication.death"] = {params = {}, tips = "", author = ""},
    ["beefalo.domestication.domesticated"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["beefalo.domestication.feed"] = {params = {}, tips = "", author = ""},
    ["beefalo.domestication.feral"] = {params = {}, tips = "", author = ""},
    ["beefalo.domestication.mountedattack"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["beefalo.domestication.mountedattacked"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["beefalo.domestication.ride"] = {params = {}, tips = "", author = ""},
    ["beefalo.domestication.start"] = {params = {}, tips = "", author = ""},
    ["begin_final_pickup"] = {params = {}, tips = "", author = ""},
    ["begin_opening"] = {params = {}, tips = "", author = ""},
    ["begin_retrieving"] = {params = {}, tips = "", author = ""},
    ["beginregrowth"] = {params = {}, tips = "", author = ""},
    ["beingridden"] = {params = {}, tips = "", author = ""},
    ["birdpoisoned"] = {params = {}, tips = "", author = ""},
    ["blocked"] = {params = {}, tips = "", author = ""},
    ["boat_start_moving"] = {params = {}, tips = "", author = ""},
    ["boat_stop_moving"] = {params = {}, tips = "", author = ""},
    ["boatcollision"] = {params = {}, tips = "", author = ""},
    ["boatmagnet_pull_start"] = {params = {}, tips = "", author = ""},
    ["boatmagnet_pull_stop"] = {params = {}, tips = "", author = ""},
    ["boatrace_finish"] = {params = {}, tips = "", author = ""},
    ["boatrace_idle_disappear"] = {params = {}, tips = "", author = ""},
    ["boatrace_setindex"] = {params = {}, tips = "", author = ""},
    ["boatrace_start"] = {params = {}, tips = "", author = ""},
    ["boatrace_starttimerended"] = {params = {}, tips = "", author = ""},
    ["boatteleport"] = {params = {}, tips = "", author = ""},
    ["breaksoil"] = {params = {}, tips = "", author = ""},
    ["brushed"] = {params = {}, tips = "", author = ""},
    ["bucked"] = {params = {}, tips = "", author = ""},
    ["bufferedcastaoe"] = {params = {}, tips = "", author = ""},
    ["builditem"] = {params = {}, tips = "", author = ""},
    ["buildstructure"] = {params = {}, tips = "", author = ""},
    ["buildsuccess"] = {params = {}, tips = "", author = ""},
    ["burnt"] = {params = {}, tips = "", author = ""},
    ["burntup"] = {params = {}, tips = "", author = ""},
    ["call_guards"] = {params = {}, tips = "", author = ""},
    ["calling_moon_relics"] = {params = {}, tips = "", author = ""},
    ["cancel_channel_longaction"] = {params = {}, tips = "", author = ""},
    ["cancelcatch"] = {params = {}, tips = "", author = ""},
    ["cancelmovementprediction"] = {params = {}, tips = "", author = ""},
    ["cancelrefreshcrafting"] = {params = {}, tips = "", author = ""},
    ["cantbuild"] = {params = {}, tips = "", author = ""},
    ["carefulwalking"] = {params = {}, tips = "", author = ""},
    ["carnivalgame_endofround"] = {params = {}, tips = "", author = ""},
    ["carnivalgame_feedchicks_available"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_feedchicks_feed"] = {params = {}, tips = "", author = ""},
    ["carnivalgame_feedchicks_hungry"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_herding_arivedhome"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_herding_gothome"] = {params = {}, tips = "", author = ""},
    ["carnivalgame_memory_cardrevealed"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_memory_cardstartround"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_memory_revealcard"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_shooting_shoot"] = {params = {}, tips = "", author = ""},
    ["carnivalgame_shooting_target_hit"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_target_startround"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["carnivalgame_turnoff"] = {params = {}, tips = "", author = ""},
    ["carnivalgame_turnon"] = {params = {}, tips = "", author = ""},
    ["carrat_error_direction"] = {params = {}, tips = "", author = ""},
    ["carrat_error_sleeping"] = {params = {}, tips = "", author = ""},
    ["carrat_error_walking"] = {params = {}, tips = "", author = ""},
    ["carratboarded"] = {params = {}, tips = "", author = ""},
    ["catapultspeedboost"] = {params = {}, tips = "", author = ""},
    ["catch"] = {params = {}, tips = "", author = ""},
    ["caught"] = {params = {}, tips = "", author = ""},
    ["ccoverrides"] = {params = {}, tips = "", author = ""},
    ["ccphasefn"] = {params = {}, tips = "", author = ""},
    ["changearea"] = {params = {}, tips = "", author = ""},
    ["changefiredamage"] = {params = {}, tips = "", author = ""},
    ["channel_finished"] = {params = {}, tips = "", author = ""},
    ["character.prototyped"] = {params = {}, tips = "", author = ""},
    ["charliecutscene"] = {params = {}, tips = "", author = ""},
    ["cheating"] = {params = {}, tips = "", author = ""},
    ["checkpoint_found"] = {params = {}, tips = "", author = ""},
    ["cheer"] = {params = {}, tips = "", author = ""},
    ["childgoinghome"] = {params = {}, tips = "", author = ""},
    ["chomp"] = {params = {}, tips = "", author = ""},
    ["chomped"] = {params = {}, tips = "", author = ""},
    ["ck_breach"] = {params = {}, tips = "", author = ""},
    ["ck_loadcannon"] = {params = {}, tips = "", author = ""},
    ["ck_shootcannon"] = {params = {}, tips = "", author = ""},
    ["ck_spawn"] = {params = {}, tips = "", author = ""},
    ["ck_taunt"] = {params = {}, tips = "", author = ""},
    ["claw_interact_ground"] = {params = {}, tips = "", author = ""},
    ["clienthealthdirty"] = {params = {}, tips = "", author = ""},
    ["clienthealthstatusdirty"] = {params = {}, tips = "", author = ""},
    ["clientpethealthdirty"] = {params = {}, tips = "", author = ""},
    ["clientpethealthpulsedirty"] = {params = {}, tips = "", author = ""},
    ["clientpethealthstatusdirty"] = {params = {}, tips = "", author = ""},
    ["clientpethealthsymboldirty"] = {params = {}, tips = "", author = ""},
    ["clientpetmaxhealthdirty"] = {params = {}, tips = "", author = ""},
    ["clientpetskindirty"] = {params = {}, tips = "", author = ""},
    ["clientsideinventoryflagschanged"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["clocksegschanged"] = {params = {}, tips = "", author = ""},
    ["clocktick"] = {params = {}, tips = "", author = ""},
    ["close_meter"] = {params = {}, tips = "", author = ""},
    ["closecontainer"] = {params = {}, tips = "", author = ""},
    ["closespellwheel"] = {params = {}, tips = "", author = ""},
    ["coach"] = {params = {}, tips = "", author = ""},
    ["cocoon_destroyed"] = {params = {}, tips = "", author = ""},
    ["collapsesoil"] = {params = {}, tips = "", author = ""},
    ["collision_stun"] = {params = {}, tips = "", author = ""},
    ["colourtweener_end"] = {params = {}, tips = "", author = ""},
    ["colourtweener_start"] = {params = {}, tips = "", author = ""},
    ["combat_lunge"] = {params = {}, tips = "", author = ""},
    ["combat_parry"] = {params = {}, tips = "", author = ""},
    ["cometo"] = {params = {}, tips = "", author = ""},
    ["command"] = {params = {}, tips = "", author = ""},
    ["community_clientdata_updated"] = {params = {}, tips = "", author = ""},
    ["community_progression_request_complete"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["community_quest_request_complete"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["consumehealthcost"] = {params = {}, tips = "", author = ""},
    ["consumeingredients"] = {params = {}, tips = "", author = ""},
    ["contestdisabled"] = {params = {}, tips = "", author = ""},
    ["contestenabled"] = {params = {}, tips = "", author = ""},
    ["conteststarted"] = {params = {}, tips = "", author = ""},
    ["continuefrompause"] = {params = {}, tips = "", author = ""},
    ["continuework"] = {params = {}, tips = "", author = ""},
    ["coveredinbees"] = {params = {}, tips = "", author = ""},
    ["creepactivate"] = {params = {}, tips = "", author = ""},
    ["critter_avoidcombat"] = {params = {}, tips = "", author = ""},
    ["critter_onnuzzle"] = {params = {}, tips = "", author = ""},
    ["critter_onpet"] = {params = {}, tips = "", author = ""},
    ["critterplaywithme"] = {params = {}, tips = "", author = ""},
    ["crittertraitchanged"] = {params = {}, tips = "", author = ""},
    ["cycleschanged"] = {params = {}, tips = "", author = ""},
    ["damaged"] = {params = {}, tips = "", author = ""},
    ["damageresisted"] = {params = {}, tips = "", author = ""},
    ["dance"] = {params = {}, tips = "", author = ""},
    ["dancingplayer"] = {params = {}, tips = "", author = ""},
    ["dancingplayerdata"] = {params = {}, tips = "", author = ""},
    ["daywalkerchainbreak"] = {params = {}, tips = "", author = ""},
    ["deactivateworld"] = {params = {}, tips = "", author = ""},
    ["dead_otterden_added"] = {params = {}, tips = "", author = ""},
    ["death"] = {params = {}, tips = "", author = ""},
    ["deercast"] = {params = {}, tips = "", author = ""},
    ["deerherdmigration"] = {params = {}, tips = "", author = ""},
    ["defend_farm_plant"] = {params = {}, tips = "", author = ""},
    ["deinked"] = {params = {}, tips = "", author = ""},
    ["demutated"] = {params = {}, tips = "", author = ""},
    ["depart"] = {params = {}, tips = "", author = ""},
    ["deployitem"] = {params = {}, tips = "", author = ""},
    ["despawn"] = {params = {}, tips = "", author = ""},
    ["despawnedfromhaunt"] = {params = {}, tips = "", author = ""},
    ["detachchild"] = {params = {}, tips = "", author = ""},
    ["digtolocation"] = {params = {}, tips = "", author = ""},
    ["disappoint"] = {params = {}, tips = "", author = ""},
    ["dismount"] = {params = {}, tips = "", author = ""},
    ["dismounted"] = {params = {}, tips = "", author = ""},
    ["dispell_shadow_pillars"] = {params = {}, tips = "", author = ""},
    ["dive_eat"] = {params = {}, tips = "", author = ""},
    ["diveandrelocate"] = {params = {}, tips = "", author = ""},
    ["diveitem"] = {params = {}, tips = "", author = ""},
    ["do_despawn"] = {params = {}, tips = "", author = ""},
    ["do_robot_spark"] = {params = {}, tips = "", author = ""},
    ["doattack"] = {params = {}, tips = "", author = ""},
    ["dobite"] = {params = {}, tips = "", author = ""},
    ["dobreach"] = {params = {}, tips = "", author = ""},
    ["docollapse"] = {params = {}, tips = "", author = ""},
    ["docollect"] = {params = {}, tips = "", author = ""},
    ["docrystalspawnin"] = {params = {}, tips = "", author = ""},
    ["doelementalvolley"] = {params = {}, tips = "", author = ""},
    ["doerode"] = {params = {}, tips = "", author = ""},
    ["doexperiment"] = {params = {}, tips = "", author = ""},
    ["doicegrow"] = {params = {}, tips = "", author = ""},
    ["doleapattack"] = {params = {}, tips = "", author = ""},
    ["doleave"] = {params = {}, tips = "", author = ""},
    ["dolure"] = {params = {}, tips = "", author = ""},
    ["domesticated"] = {params = {}, tips = "", author = ""},
    ["domesticationdelta"] = {params = {}, tips = "", author = ""},
    ["done_embark_movement"] = {params = {}, tips = "", author = ""},
    ["doneexperiment"] = {params = {}, tips = "", author = ""},
    ["donetalking"] = {params = {}, tips = "", author = ""},
    ["doneteleporting"] = {params = {}, tips = "", author = ""},
    ["dosplash"] = {params = {}, tips = "", author = ""},
    ["doswoop"] = {params = {}, tips = "", author = ""},
    ["dovolley"] = {params = {}, tips = "", author = ""},
    ["dragonflyengaged"] = {params = {}, tips = "", author = ""},
    ["dressedup"] = {params = {}, tips = "", author = ""},
    ["dropallaggro"] = {params = {}, tips = "", author = ""},
    ["dropitem"] = {params = {}, tips = "", author = ""},
    ["dropkey"] = {params = {}, tips = "", author = ""},
    ["droppedtarget"] = {params = {}, tips = "", author = ""},
    ["dropraisedboulder"] = {params = {}, tips = "", author = ""},
    ["dustmothden_repaired"] = {params = {}, tips = "", author = ""},
    ["dustmothsearch"] = {params = {}, tips = "", author = ""},
    ["earlyexit"] = {params = {}, tips = "", author = ""},
    ["eat"] = {params = {}, tips = "", author = ""},
    ["eat_food"] = {params = {}, tips = "", author = ""},
    ["eatrocks"] = {params = {}, tips = "", author = ""},
    ["emerge"] = {params = {}, tips = "", author = ""},
    ["emote"] = {params = {}, tips = "", author = ""},
    ["enableboatcamera"] = {params = {}, tips = "", author = ""},
    ["enabledynamicmusic"] = {params = {}, tips = "", author = ""},
    ["enablemovementprediction"] = {params = {}, tips = "", author = ""},
    ["encumberedwalking"] = {params = {}, tips = "", author = ""},
    ["endloop"] = {params = {}, tips = "", author = ""},
    ["endofmatch"] = {params = {}, tips = "", author = ""},
    ["endquake"] = {params = {}, tips = "", author = ""},
    ["endrest"] = {params = {}, tips = "", author = ""},
    ["endsteeringreticule"] = {params = {}, tips = "", author = ""},
    ["endtraining"] = {params = {}, tips = "", author = ""},
    ["endtraps"] = {params = {}, tips = "", author = ""},
    ["energylevelupdate"] = {params = {}, tips = "", author = ""},
    ["engineeringcircuitchanged"] = {params = {}, tips = "", author = ""},
    ["enrage"] = {params = {}, tips = "", author = ""},
    ["entercharacterselect"] = {params = {}, tips = "", author = ""},
    ["enterlimbo"] = {params = {}, tips = "", author = ""},
    ["entermood"] = {params = {}, tips = "", author = ""},
    ["enterraindome"] = {params = {}, tips = "", author = ""},
    ["entershield"] = {params = {}, tips = "", author = ""},
    ["entity_death"] = {params = {}, tips = "", author = ""},
    ["entity_droploot"] = {params = {}, tips = "", author = ""},
    ["entity_spawned"] = {params = {}, tips = "", author = ""},
    ["entitysleep"] = {params = {}, tips = "", author = ""},
    ["entitywake"] = {params = {}, tips = "", author = ""},
    ["epicscare"] = {params = {}, tips = "", author = ""},
    ["equip"] = {params = {}, tips = "", author = ""},
    ["equipped"] = {params = {}, tips = "", author = ""},
    ["equipskinneditem"] = {params = {}, tips = "", author = ""},
    ["exit"] = {params = {}, tips = "", author = ""},
    ["exitlimbo"] = {params = {}, tips = "", author = ""},
    ["exitraindome"] = {params = {}, tips = "", author = ""},
    ["exitshield"] = {params = {}, tips = "", author = ""},
    ["explosion"] = {params = {}, tips = "", author = ""},
    ["fail_fx"] = {params = {}, tips = "", author = ""},
    ["fallapart"] = {params = {}, tips = "", author = ""},
    ["feasterfinished"] = {params = {}, tips = "", author = ""},
    ["feasterstarted"] = {params = {}, tips = "", author = ""},
    ["feastinterrupted"] = {params = {}, tips = "", author = ""},
    ["feedincontainer"] = {params = {}, tips = "", author = ""},
    ["feetslipped"] = {params = {}, tips = "", author = ""},
    ["fencerotated"] = {params = {}, tips = "", author = ""},
    ["finish_rift"] = {params = {}, tips = "", author = ""},
    ["finished_leaving"] = {params = {}, tips = "", author = ""},
    ["finishedwork"] = {params = {}, tips = "", author = ""},
    ["finishplowing"] = {params = {}, tips = "", author = ""},
    ["finishseamlessplayerswap"] = {params = {}, tips = "", author = ""},
    ["firedamage"] = {params = {}, tips = "", author = ""},
    ["firemelt"] = {params = {}, tips = "", author = ""},
    ["fishcaught"] = {params = {}, tips = "", author = ""},
    ["fishingcancel"] = {params = {}, tips = "", author = ""},
    ["fishingcatch"] = {params = {}, tips = "", author = ""},
    ["fishingcollect"] = {params = {}, tips = "", author = ""},
    ["fishingloserod"] = {params = {}, tips = "", author = ""},
    ["fishingnibble"] = {params = {}, tips = "", author = ""},
    ["fishingstrain"] = {params = {}, tips = "", author = ""},
    ["flee"] = {params = {}, tips = "", author = ""},
    ["fleewarning"] = {params = {}, tips = "", author = ""},
    ["flinch"] = {params = {}, tips = "", author = ""},
    ["floater_startfloating"] = {params = {}, tips = "", author = ""},
    ["floater_stopfloating"] = {params = {}, tips = "", author = ""},
    ["fly_back"] = {params = {}, tips = "", author = ""},
    ["flyaway"] = {params = {}, tips = "", author = ""},
    ["flyback"] = {params = {}, tips = "", author = ""},
    ["foodbuffattached"] = {params = {}, tips = "", author = ""},
    ["foodbuffdetached"] = {params = {}, tips = "", author = ""},
    ["forcefinishterraforming"] = {params = {}, tips = "", author = ""},
    ["forceperishchange"] = {params = {}, tips = "", author = ""},
    ["forgetinventoryitem"] = {params = {}, tips = "", author = ""},
    ["forgetme"] = {params = {}, tips = "", author = ""},
    ["fossilfeast"] = {params = {}, tips = "", author = ""},
    ["fossilsnare"] = {params = {}, tips = "", author = ""},
    ["found_by_boatrace_checker"] = {params = {}, tips = "", author = ""},
    ["freesoulhopschanged"] = {params = {}, tips = "", author = ""},
    ["freeze"] = {params = {}, tips = "", author = ""},
    ["freshspawn"] = {params = {}, tips = "", author = ""},
    ["friend_level_changed"] = {params = {}, tips = "", author = ""},
    ["friend_task_complete"] = {params = {}, tips = "", author = ""},
    ["fueltaken"] = {params = {}, tips = "", author = ""},
    ["full_retreat"] = {params = {}, tips = "", author = ""},
    ["fx_spawned"] = {params = {}, tips = "", author = ""},
    ["gainloyalty"] = {params = {}, tips = "", author = ""},
    ["gainrainimmunity"] = {params = {}, tips = "", author = ""},
    ["getup"] = {params = {}, tips = "", author = ""},
    ["ghostdissipated"] = {params = {}, tips = "", author = ""},
    ["ghostlybond_level_change"] = {params = {}, tips = "", author = ""},
    ["ghostvision"] = {params = {}, tips = "", author = ""},
    ["giftreceiverupdate"] = {params = {}, tips = "", author = ""},
    ["givetarget"] = {params = {}, tips = "", author = ""},
    ["giveuptarget"] = {params = {}, tips = "", author = ""},
    ["gobacktocave"] = {params = {}, tips = "", author = ""},
    ["goenlightened"] = {params = {}, tips = "", author = ""},
    ["gogglevision"] = {params = {}, tips = "", author = ""},
    ["gohome"] = {params = {}, tips = "", author = ""},
    ["gohomefailed"] = {params = {}, tips = "", author = ""},
    ["goinghome"] = {params = {}, tips = "", author = ""},
    ["goinsane"] = {params = {}, tips = "", author = ""},
    ["goneferal"] = {params = {}, tips = "", author = ""},
    ["gosane"] = {params = {}, tips = "", author = ""},
    ["gosmall"] = {params = {}, tips = "", author = ""},
    ["got_off_platform"] = {params = {}, tips = "", author = ""},
    ["got_on_platform"] = {params = {}, tips = "", author = ""},
    ["gotcommander"] = {params = {}, tips = "", author = ""},
    ["gotnewattunement"] = {params = {}, tips = "", author = ""},
    ["gotnewitem"] = {params = {}, tips = "", author = ""},
    ["gotosleep"] = {params = {}, tips = "", author = ""},
    ["gotyotrtoken"] = {params = {}, tips = "", author = ""},
    ["growantler"] = {params = {}, tips = "", author = ""},
    ["growfrombutterfly"] = {params = {}, tips = "", author = ""},
    ["handfinished"] = {params = {}, tips = "", author = ""},
    ["harvestsomething"] = {params = {}, tips = "", author = ""},
    ["harvesttrap"] = {params = {}, tips = "", author = ""},
    ["harvesttrapsouls"] = {params = {}, tips = "", author = ""},
    ["hasinspirationbuff"] = {params = {}, tips = "", author = ""},
    ["hasslerkilled"] = {params = {}, tips = "", author = ""},
    ["hasslerremoved"] = {params = {}, tips = "", author = ""},
    ["haunt"] = {params = {}, tips = "", author = ""},
    ["health_transform"] = {params = {}, tips = "", author = ""},
    ["healthdelta"] = {params = {}, tips = "", author = ""},
    ["heardhorn"] = {params = {}, tips = "", author = ""},
    ["hide"] = {params = {}, tips = "", author = ""},
    ["hide_warp_marker"] = {params = {}, tips = "", author = ""},
    ["hideandseek_start"] = {params = {}, tips = "", author = ""},
    ["hidebait"] = {params = {}, tips = "", author = ""},
    ["hidevotedialog"] = {params = {}, tips = "", author = ""},
    ["hideworldreset"] = {params = {}, tips = "", author = ""},
    ["hit"] = {params = {}, tips = "", author = ""},
    ["hit_boat"] = {params = {}, tips = "", author = ""},
    ["hitchto"] = {params = {}, tips = "", author = ""},
    ["home_upgraded"] = {params = {}, tips = "", author = ""},
    ["hostileprojectile"] = {params = {}, tips = "", author = ""},
    ["hounded_setdifficulty"] = {params = {}, tips = "", author = ""},
    ["hounded_setsummervariant"] = {params = {}, tips = "", author = ""},
    ["hounded_setwintervariant"] = {params = {}, tips = "", author = ""},
    ["houndwarning"] = {params = {}, tips = "", author = ""},
    ["hungerdelta"] = {params = {}, tips = "", author = ""},
    ["hungrybuild"] = {params = {}, tips = "", author = ""},
    ["huntbeastnearby"] = {params = {}, tips = "", author = ""},
    ["huntlosttrail"] = {params = {}, tips = "", author = ""},
    ["huntstartfork"] = {params = {}, tips = "", author = ""},
    ["huntsuccessfulfork"] = {params = {}, tips = "", author = ""},
    ["huntwrongfork"] = {params = {}, tips = "", author = ""},
    ["icefloebreak"] = {params = {}, tips = "", author = ""},
    ["idplantseed"] = {params = {}, tips = "", author = ""},
    ["ifnotchanceloot"] = {params = {}, tips = "", author = ""},
    ["imagechange"] = {params = {}, tips = "", author = ""},
    ["incoming_jump"] = {params = {}, tips = "", author = ""},
    ["inducedinsanity"] = {params = {}, tips = "", author = ""},
    ["inevitabledeath"] = {params = {}, tips = "", author = ""},
    ["inked"] = {params = {}, tips = "", author = ""},
    ["inmightygym"] = {params = {}, tips = "", author = ""},
    ["inspectaclesgamechanged"] = {params = {}, tips = "", author = ""},
    ["inspectaclesping"] = {params = {}, tips = "", author = ""},
    ["inspectaclesvision"] = {params = {}, tips = "", author = ""},
    ["inspirationdelta"] = {params = {}, tips = "", author = ""},
    ["inspirationsongchanged"] = {params = {}, tips = "", author = ""},
    ["introover"] = {params = {}, tips = "", author = ""},
    ["invalidrpc"] = {params = {}, tips = "", author = ""},
    ["inventoryclosed"] = {params = {}, tips = "", author = ""},
    ["inventoryfull"] = {params = {}, tips = "", author = ""},
    ["inventoryitem_stacksizedirty"] = {params = {}, tips = "", author = ""},
    ["inventoryitem_updatespecifictooltip"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["inventoryitem_updatetooltip"] = {params = {}, tips = "", author = ""},
    ["invincibletoggle"] = {params = {}, tips = "", author = ""},
    ["ipecacpoop"] = {params = {}, tips = "", author = ""},
    ["isacidsizzling"] = {params = {}, tips = "", author = ""},
    ["isfeasting"] = {params = {}, tips = "", author = ""},
    ["itemget"] = {params = {}, tips = "", author = ""},
    ["itemlose"] = {params = {}, tips = "", author = ""},
    ["itemplanted"] = {params = {}, tips = "", author = ""},
    ["itemranout"] = {params = {}, tips = "", author = ""},
    ["jump"] = {params = {}, tips = "", author = ""},
    ["killed"] = {params = {}, tips = "", author = ""},
    ["kitcoonplaywithme"] = {params = {}, tips = "", author = ""},
    ["knockback"] = {params = {}, tips = "", author = ""},
    ["knockbackdropped"] = {params = {}, tips = "", author = ""},
    ["knockedout"] = {params = {}, tips = "", author = ""},
    ["lantern_off"] = {params = {}, tips = "", author = ""},
    ["lantern_on"] = {params = {}, tips = "", author = ""},
    ["laugh"] = {params = {}, tips = "", author = ""},
    ["lavaarena_talk"] = {params = {}, tips = "", author = ""},
    ["leap"] = {params = {}, tips = "", author = ""},
    ["learncookbookrecipe"] = {params = {}, tips = "", author = ""},
    ["learncookbookstats"] = {params = {}, tips = "", author = ""},
    ["learnfertilizer"] = {params = {}, tips = "", author = ""},
    ["learnmap"] = {params = {}, tips = "", author = ""},
    ["learnplantstage"] = {params = {}, tips = "", author = ""},
    ["learnrecipe"] = {params = {}, tips = "", author = ""},
    ["leave"] = {params = {}, tips = "", author = ""},
    ["leavemood"] = {params = {}, tips = "", author = ""},
    ["leechattached"] = {params = {}, tips = "", author = ""},
    ["levelup"] = {params = {}, tips = "", author = ""},
    ["lift_gym"] = {params = {}, tips = "", author = ""},
    ["lightningdamageavoided"] = {params = {}, tips = "", author = ""},
    ["lightningstrike"] = {params = {}, tips = "", author = ""},
    ["linkmushroomsprout"] = {params = {}, tips = "", author = ""},
    ["linktoadstool"] = {params = {}, tips = "", author = ""},
    ["linktownportals"] = {params = {}, tips = "", author = ""},
    ["lobbyplayerspawndelay"] = {params = {}, tips = "", author = ""},
    ["locomote"] = {params = {}, tips = "", author = ""},
    ["loot_prefab_spawned"] = {params = {}, tips = "", author = ""},
    ["loseloyalty"] = {params = {}, tips = "", author = ""},
    ["loserainimmunity"] = {params = {}, tips = "", author = ""},
    ["lostcommander"] = {params = {}, tips = "", author = ""},
    ["lostfruitdragonchallenge"] = {params = {}, tips = "", author = ""},
    ["losttarget"] = {params = {}, tips = "", author = ""},
    ["lowering_anchor"] = {params = {}, tips = "", author = ""},
    ["lunar_grazer_despawn"] = {params = {}, tips = "", author = ""},
    ["lunar_grazer_respawn"] = {params = {}, tips = "", author = ""},
    ["lunarrift_opened"] = {params = {}, tips = "", author = ""},
    ["lunarthrallplant_infested"] = {params = {}, tips = "", author = ""},
    ["magicianstopped"] = {params = {}, tips = "", author = ""},
    ["makefriend"] = {params = {}, tips = "", author = ""},
    ["makenewnest"] = {params = {}, tips = "", author = ""},
    ["makeplayerghost"] = {params = {}, tips = "", author = ""},
    ["makerecipe"] = {params = {}, tips = "", author = ""},
    ["malbatrossremoved"] = {params = {}, tips = "", author = ""},
    ["mast_burnt"] = {params = {}, tips = "", author = ""},
    ["mast_lamp_off"] = {params = {}, tips = "", author = ""},
    ["mast_lamp_on"] = {params = {}, tips = "", author = ""},
    ["master_autosaverupdate"] = {params = {}, tips = "", author = ""},
    ["master_clockupdate"] = {params = {}, tips = "", author = ""},
    ["master_seasonsupdate"] = {params = {}, tips = "", author = ""},
    ["master_shardbossdefeated"] = {params = {}, tips = "", author = ""},
    ["master_shardmermkingcrown"] = {params = {}, tips = "", author = ""},
    ["master_shardmermkingexists"] = {params = {}, tips = "", author = ""},
    ["master_shardmermkingpauldron"] = {params = {}, tips = "", author = ""},
    ["master_shardmermkingtrident"] = {params = {}, tips = "", author = ""},
    ["master_sinkholesupdate"] = {params = {}, tips = "", author = ""},
    ["master_worldresetupdate"] = {params = {}, tips = "", author = ""},
    ["master_worldvoterenabled"] = {params = {}, tips = "", author = ""},
    ["master_worldvotersquelchedupdate"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["master_worldvoterupdate"] = {params = {}, tips = "", author = ""},
    ["matchover"] = {params = {}, tips = "", author = ""},
    ["megaflare_detonated"] = {params = {}, tips = "", author = ""},
    ["merm_use_building"] = {params = {}, tips = "", author = ""},
    ["messagebottletreasure_marker_added"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["messagebottletreasure_marker_removed"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["miasma_setactive"] = {params = {}, tips = "", author = ""},
    ["miasmacloudexists"] = {params = {}, tips = "", author = ""},
    ["miasmalevel"] = {params = {}, tips = "", author = ""},
    ["mightiness_statechange"] = {params = {}, tips = "", author = ""},
    ["mightinessdelta"] = {params = {}, tips = "", author = ""},
    ["migration_activate"] = {params = {}, tips = "", author = ""},
    ["migration_activate_other"] = {params = {}, tips = "", author = ""},
    ["migration_available"] = {params = {}, tips = "", author = ""},
    ["migration_full"] = {params = {}, tips = "", author = ""},
    ["migration_unavailable"] = {params = {}, tips = "", author = ""},
    ["mindcontrolled"] = {params = {}, tips = "", author = ""},
    ["mindcontrollevel"] = {params = {}, tips = "", author = ""},
    ["minhealth"] = {params = {}, tips = "", author = ""},
    ["minigame_spectator_start_outro"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["minionchange"] = {params = {}, tips = "", author = ""},
    ["miniondeath"] = {params = {}, tips = "", author = ""},
    ["moistureceilchanged"] = {params = {}, tips = "", author = ""},
    ["moisturedelta"] = {params = {}, tips = "", author = ""},
    ["molehill_dug_up"] = {params = {}, tips = "", author = ""},
    ["monkeycursehit"] = {params = {}, tips = "", author = ""},
    ["monkeydanger"] = {params = {}, tips = "", author = ""},
    ["moonboss_defeated"] = {params = {}, tips = "", author = ""},
    ["moonfissurevent"] = {params = {}, tips = "", author = ""},
    ["moonpetrify"] = {params = {}, tips = "", author = ""},
    ["moonphasechanged"] = {params = {}, tips = "", author = ""},
    ["moonphasechanged2"] = {params = {}, tips = "", author = ""},
    ["moonphasestylechanged"] = {params = {}, tips = "", author = ""},
    ["moonstorm_nodes_dirty_relay"] = {params = {}, tips = "", author = ""},
    ["moonstormlevel"] = {params = {}, tips = "", author = ""},
    ["moontransformed"] = {params = {}, tips = "", author = ""},
    ["morph"] = {params = {}, tips = "", author = ""},
    ["motd_image_loaded"] = {params = {}, tips = "", author = ""},
    ["motd_info_loaded"] = {params = {}, tips = "", author = ""},
    ["mounted"] = {params = {}, tips = "", author = ""},
    ["mounthurt"] = {params = {}, tips = "", author = ""},
    ["mountwounded"] = {params = {}, tips = "", author = ""},
    ["mouseout"] = {params = {}, tips = "", author = ""},
    ["mouseover"] = {params = {}, tips = "", author = ""},
    ["moveback"] = {params = {}, tips = "", author = ""},
    ["moveforward"] = {params = {}, tips = "", author = ""},
    ["ms_addgiftreceiver"] = {params = {}, tips = "", author = ""},
    ["ms_advanceseason"] = {params = {}, tips = "", author = ""},
    ["ms_archivesbreached"] = {params = {}, tips = "", author = ""},
    ["ms_becameghost"] = {params = {}, tips = "", author = ""},
    ["ms_cancelminigame"] = {params = {}, tips = "", author = ""},
    ["ms_carnivalplazabuilt"] = {params = {}, tips = "", author = ""},
    ["ms_carnivalplazadestroyed"] = {params = {}, tips = "", author = ""},
    ["ms_cleanedupsharkboiarena"] = {params = {}, tips = "", author = ""},
    ["ms_cleanupticksharkboiarena"] = {params = {}, tips = "", author = ""},
    ["ms_clientauthenticationcomplete"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_clientdisconnected"] = {params = {}, tips = "", author = ""},
    ["ms_closepopup"] = {params = {}, tips = "", author = ""},
    ["ms_closepopups"] = {params = {}, tips = "", author = ""},
    ["ms_collect_uniquekitcoons"] = {params = {}, tips = "", author = ""},
    ["ms_collectallkitcoons"] = {params = {}, tips = "", author = ""},
    ["ms_collecthiddenkitcoons"] = {params = {}, tips = "", author = ""},
    ["ms_cyclecomplete"] = {params = {}, tips = "", author = ""},
    ["ms_deltamoisture"] = {params = {}, tips = "", author = ""},
    ["ms_deltawetness"] = {params = {}, tips = "", author = ""},
    ["ms_despawn_wagstaff_npc_pstboss"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_doneopengift"] = {params = {}, tips = "", author = ""},
    ["ms_enableresourcerenewal"] = {params = {}, tips = "", author = ""},
    ["ms_exchangeshadowcreature"] = {params = {}, tips = "", author = ""},
    ["ms_forcenaughtiness"] = {params = {}, tips = "", author = ""},
    ["ms_forcenightmarestate"] = {params = {}, tips = "", author = ""},
    ["ms_forceprecipitation"] = {params = {}, tips = "", author = ""},
    ["ms_forcequake"] = {params = {}, tips = "", author = ""},
    ["ms_fruitflyspawneractive"] = {params = {}, tips = "", author = ""},
    ["ms_fruitflytimerfinished"] = {params = {}, tips = "", author = ""},
    ["ms_giftopened"] = {params = {}, tips = "", author = ""},
    ["ms_joinsquad_"] = {params = {}, tips = "", author = ""},
    ["ms_junkstolen"] = {params = {}, tips = "", author = ""},
    ["ms_lavaarena_endofstage"] = {params = {}, tips = "", author = ""},
    ["ms_leavesquad_"] = {params = {}, tips = "", author = ""},
    ["ms_lockmoonphase"] = {params = {}, tips = "", author = ""},
    ["ms_locknightmarephase"] = {params = {}, tips = "", author = ""},
    ["ms_lordfruitflykilled"] = {params = {}, tips = "", author = ""},
    ["ms_lunarportal_removed"] = {params = {}, tips = "", author = ""},
    ["ms_lunarrift_maxsize"] = {params = {}, tips = "", author = ""},
    ["ms_minigamedeactivated"] = {params = {}, tips = "", author = ""},
    ["ms_miniquake"] = {params = {}, tips = "", author = ""},
    ["ms_moonboss_was_defeated"] = {params = {}, tips = "", author = ""},
    ["ms_moonportalproximity"] = {params = {}, tips = "", author = ""},
    ["ms_moonstormwindowover"] = {params = {}, tips = "", author = ""},
    ["ms_newmastersessionid"] = {params = {}, tips = "", author = ""},
    ["ms_newplayercharacterspawned"] = {params = {}, tips = "", author = ""},
    ["ms_newplayerspawned"] = {params = {}, tips = "", author = ""},
    ["ms_nextcycle"] = {params = {}, tips = "", author = ""},
    ["ms_nextnightmarephase"] = {params = {}, tips = "", author = ""},
    ["ms_nextphase"] = {params = {}, tips = "", author = ""},
    ["ms_oncroprotted"] = {params = {}, tips = "", author = ""},
    ["ms_onportalrez"] = {params = {}, tips = "", author = ""},
    ["ms_opengift"] = {params = {}, tips = "", author = ""},
    ["ms_playercounts"] = {params = {}, tips = "", author = ""},
    ["ms_playerdespawn"] = {params = {}, tips = "", author = ""},
    ["ms_playerdespawnanddelete"] = {params = {}, tips = "", author = ""},
    ["ms_playerdespawnandmigrate"] = {params = {}, tips = "", author = ""},
    ["ms_playerdisconnected"] = {params = {}, tips = "", author = ""},
    ["ms_playerjoined"] = {params = {}, tips = "", author = ""},
    ["ms_playerleft"] = {params = {}, tips = "", author = ""},
    ["ms_playerreroll"] = {params = {}, tips = "", author = ""},
    ["ms_playerseamlessswaped"] = {params = {}, tips = "", author = ""},
    ["ms_playerspawn"] = {params = {}, tips = "", author = ""},
    ["ms_receivevote"] = {params = {}, tips = "", author = ""},
    ["ms_register_for_damage_tracking"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_register_junk_pile_big"] = {params = {}, tips = "", author = ""},
    ["ms_register_lavaarenacenter"] = {params = {}, tips = "", author = ""},
    ["ms_register_retrofitted_grotterwar_homepoint"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_register_retrofitted_grotterwar_spawnpoint"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_register_wagstaff_machinery"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_registerdaywalkerspawningground"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["ms_registerdeerspawningground"] = {params = {}, tips = "", author = ""},
    ["ms_registerfishshoal"] = {params = {}, tips = "", author = ""},
    ["ms_registergrottopool"] = {params = {}, tips = "", author = ""},
    ["ms_registerklaussack"] = {params = {}, tips = "", author = ""},
    ["ms_registerlavapond"] = {params = {}, tips = "", author = ""},
    ["ms_registermigrationportal"] = {params = {}, tips = "", author = ""},
    ["ms_registernightlight"] = {params = {}, tips = "", author = ""},
    ["ms_registeroasis"] = {params = {}, tips = "", author = ""},
    ["ms_registerpetrifiable"] = {params = {}, tips = "", author = ""},
    ["ms_registersoildrinker"] = {params = {}, tips = "", author = ""},
    ["ms_registerspawnpoint"] = {params = {}, tips = "", author = ""},
    ["ms_registertoadstoolspawner"] = {params = {}, tips = "", author = ""},
    ["ms_registertownportal"] = {params = {}, tips = "", author = ""},
    ["ms_registerwinonateleportpad"] = {params = {}, tips = "", author = ""},
    ["ms_removegiftreceiver"] = {params = {}, tips = "", author = ""},
    ["ms_requestedlobbycharacter"] = {params = {}, tips = "", author = ""},
    ["ms_respawnedfromghost"] = {params = {}, tips = "", author = ""},
    ["ms_restoreklaussackkey"] = {params = {}, tips = "", author = ""},
    ["ms_retreatseason"] = {params = {}, tips = "", author = ""},
    ["ms_riftaddedtopool"] = {params = {}, tips = "", author = ""},
    ["ms_riftremovedfrompool"] = {params = {}, tips = "", author = ""},
    ["ms_save"] = {params = {}, tips = "", author = ""},
    ["ms_seamlesscharacterspawned"] = {params = {}, tips = "", author = ""},
    ["ms_sendlightningstrike"] = {params = {}, tips = "", author = ""},
    ["ms_setclocksegs"] = {params = {}, tips = "", author = ""},
    ["ms_setlightningdelay"] = {params = {}, tips = "", author = ""},
    ["ms_setlightningmode"] = {params = {}, tips = "", author = ""},
    ["ms_setmoisturescale"] = {params = {}, tips = "", author = ""},
    ["ms_setmoonphase"] = {params = {}, tips = "", author = ""},
    ["ms_setmoonphasestyle"] = {params = {}, tips = "", author = ""},
    ["ms_setnightmarephase"] = {params = {}, tips = "", author = ""},
    ["ms_setprecipitationmode"] = {params = {}, tips = "", author = ""},
    ["ms_setseason"] = {params = {}, tips = "", author = ""},
    ["ms_setseasonlength"] = {params = {}, tips = "", author = ""},
    ["ms_setseasonsegmodifier"] = {params = {}, tips = "", author = ""},
    ["ms_setsnowlevel"] = {params = {}, tips = "", author = ""},
    ["ms_setspawnmode"] = {params = {}, tips = "", author = ""},
    ["ms_setupspecialevent"] = {params = {}, tips = "", author = ""},
    ["ms_setworldresettime"] = {params = {}, tips = "", author = ""},
    ["ms_setworldsetting"] = {params = {}, tips = "", author = ""},
    ["ms_shadowrift_maxsize"] = {params = {}, tips = "", author = ""},
    ["ms_shoalfishhooked"] = {params = {}, tips = "", author = ""},
    ["ms_shutdownspecialevent"] = {params = {}, tips = "", author = ""},
    ["ms_simunpaused"] = {params = {}, tips = "", author = ""},
    ["ms_skeletonspawn"] = {params = {}, tips = "", author = ""},
    ["ms_skilltreeinitialized"] = {params = {}, tips = "", author = ""},
    ["ms_spawnedsharkboiarena"] = {params = {}, tips = "", author = ""},
    ["ms_spawntoadstool"] = {params = {}, tips = "", author = ""},
    ["ms_startthemoonstorms"] = {params = {}, tips = "", author = ""},
    ["ms_startvote"] = {params = {}, tips = "", author = ""},
    ["ms_stopthemoonstorms"] = {params = {}, tips = "", author = ""},
    ["ms_stopvote"] = {params = {}, tips = "", author = ""},
    ["ms_stormchanged"] = {params = {}, tips = "", author = ""},
    ["ms_unlockchesspiece"] = {params = {}, tips = "", author = ""},
    ["ms_unregisterfishshoal"] = {params = {}, tips = "", author = ""},
    ["ms_unregisterpetrifiable"] = {params = {}, tips = "", author = ""},
    ["ms_unregistersoildrinker"] = {params = {}, tips = "", author = ""},
    ["ms_updateofferingpotstate"] = {params = {}, tips = "", author = ""},
    ["ms_updatesisturnstate"] = {params = {}, tips = "", author = ""},
    ["ms_worldreset"] = {params = {}, tips = "", author = ""},
    ["murdered"] = {params = {}, tips = "", author = ""},
    ["mutate"] = {params = {}, tips = "", author = ""},
    ["mutated"] = {params = {}, tips = "", author = ""},
    ["new_boatrace_indicator"] = {params = {}, tips = "", author = ""},
    ["newactiveitem"] = {params = {}, tips = "", author = ""},
    ["newcombattarget"] = {params = {}, tips = "", author = ""},
    ["newfishingtarget"] = {params = {}, tips = "", author = ""},
    ["newskillpointupdated"] = {params = {}, tips = "", author = ""},
    ["newstate"] = {params = {}, tips = "", author = ""},
    ["nightmareclocktick"] = {params = {}, tips = "", author = ""},
    ["nightmarephasechanged"] = {params = {}, tips = "", author = ""},
    ["nightmarevision"] = {params = {}, tips = "", author = ""},
    ["nightvision"] = {params = {}, tips = "", author = ""},
    ["nutrientsvision"] = {params = {}, tips = "", author = ""},
    ["obediencedelta"] = {params = {}, tips = "", author = ""},
    ["oceanfishing_stoppedfishing"] = {params = {}, tips = "", author = ""},
    ["on_"] = {params = {}, tips = "", author = ""},
    ["on_caught_in_net"] = {params = {}, tips = "", author = ""},
    ["on_collide"] = {params = {}, tips = "", author = ""},
    ["on_enter_might_gym"] = {params = {}, tips = "", author = ""},
    ["on_fissure_socket"] = {params = {}, tips = "", author = ""},
    ["on_halloweenmoonpotion_failed"] = {params = {}, tips = "", author = ""},
    ["on_landed"] = {params = {}, tips = "", author = ""},
    ["on_loot_dropped"] = {params = {}, tips = "", author = ""},
    ["on_lower_sail_boost"] = {params = {}, tips = "", author = ""},
    ["on_no_longer_landed"] = {params = {}, tips = "", author = ""},
    ["on_petted"] = {params = {}, tips = "", author = ""},
    ["on_planted"] = {params = {}, tips = "", author = ""},
    ["on_played_with"] = {params = {}, tips = "", author = ""},
    ["on_pre_net"] = {params = {}, tips = "", author = ""},
    ["on_release_from_net"] = {params = {}, tips = "", author = ""},
    ["on_reveal_map_spot_pre"] = {params = {}, tips = "", author = ""},
    ["on_reveal_map_spot_pst"] = {params = {}, tips = "", author = ""},
    ["on_salvaged"] = {params = {}, tips = "", author = ""},
    ["on_standing_on_new_leak"] = {params = {}, tips = "", author = ""},
    ["on_submerge"] = {params = {}, tips = "", author = ""},
    ["on_washed_ashore"] = {params = {}, tips = "", author = ""},
    ["onacceptfighttribute"] = {params = {}, tips = "", author = ""},
    ["onaccepttribute"] = {params = {}, tips = "", author = ""},
    ["onactivated"] = {params = {}, tips = "", author = ""},
    ["onactivateskill_client"] = {params = {}, tips = "", author = ""},
    ["onactivateskill_server"] = {params = {}, tips = "", author = ""},
    ["onaddskillxp_client"] = {params = {}, tips = "", author = ""},
    ["onaddskillxp_server"] = {params = {}, tips = "", author = ""},
    ["onalterguardianlasered"] = {params = {}, tips = "", author = ""},
    ["onareaattackother"] = {params = {}, tips = "", author = ""},
    ["onarrivedatthrone"] = {params = {}, tips = "", author = ""},
    ["onattackother"] = {params = {}, tips = "", author = ""},
    ["onbuilt"] = {params = {}, tips = "", author = ""},
    ["onburnt"] = {params = {}, tips = "", author = ""},
    ["onburntup"] = {params = {}, tips = "", author = ""},
    ["oncandidatekingarrived"] = {params = {}, tips = "", author = ""},
    ["oncastaoespell"] = {params = {}, tips = "", author = ""},
    ["onchangecanopyzone"] = {params = {}, tips = "", author = ""},
    ["onclose"] = {params = {}, tips = "", author = ""},
    ["oncloseother"] = {params = {}, tips = "", author = ""},
    ["onclothingchanged"] = {params = {}, tips = "", author = ""},
    ["onconsolehistoryitemclicked"] = {params = {}, tips = "", author = ""},
    ["onconsolehistoryupdated"] = {params = {}, tips = "", author = ""},
    ["oncreated"] = {params = {}, tips = "", author = ""},
    ["oncritterplaying"] = {params = {}, tips = "", author = ""},
    ["ondeactivateskill_client"] = {params = {}, tips = "", author = ""},
    ["ondeactivateskill_server"] = {params = {}, tips = "", author = ""},
    ["ondeconstructstructure"] = {params = {}, tips = "", author = ""},
    ["ondropped"] = {params = {}, tips = "", author = ""},
    ["oneat"] = {params = {}, tips = "", author = ""},
    ["oneaten"] = {params = {}, tips = "", author = ""},
    ["oneatsoul"] = {params = {}, tips = "", author = ""},
    ["onextinguish"] = {params = {}, tips = "", author = ""},
    ["onfedbyplayer"] = {params = {}, tips = "", author = ""},
    ["onflourishend"] = {params = {}, tips = "", author = ""},
    ["onflourishstart"] = {params = {}, tips = "", author = ""},
    ["onfueldsectionchanged"] = {params = {}, tips = "", author = ""},
    ["onhalloweenmoonmutate"] = {params = {}, tips = "", author = ""},
    ["onhidingspotremoved"] = {params = {}, tips = "", author = ""},
    ["onhistoryupdated"] = {params = {}, tips = "", author = ""},
    ["onhitother"] = {params = {}, tips = "", author = ""},
    ["onhop"] = {params = {}, tips = "", author = ""},
    ["onignite"] = {params = {}, tips = "", author = ""},
    ["onincinerated"] = {params = {}, tips = "", author = ""},
    ["onitemstolen"] = {params = {}, tips = "", author = ""},
    ["onlearnednewtacklesketch"] = {params = {}, tips = "", author = ""},
    ["onlighterlight"] = {params = {}, tips = "", author = ""},
    ["onmermkingcreated"] = {params = {}, tips = "", author = ""},
    ["onmermkingcreated_anywhere"] = {params = {}, tips = "", author = ""},
    ["onmermkingcrownadded"] = {params = {}, tips = "", author = ""},
    ["onmermkingcrownadded_anywhere"] = {params = {}, tips = "", author = ""},
    ["onmermkingcrownremoved"] = {params = {}, tips = "", author = ""},
    ["onmermkingcrownremoved_anywhere"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["onmermkingdestroyed"] = {params = {}, tips = "", author = ""},
    ["onmermkingdestroyed_anywhere"] = {params = {}, tips = "", author = ""},
    ["onmermkingpauldronadded"] = {params = {}, tips = "", author = ""},
    ["onmermkingpauldronadded_anywhere"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["onmermkingpauldronremoved"] = {params = {}, tips = "", author = ""},
    ["onmermkingpauldronremoved_anywhere"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["onmermkingtridentadded"] = {params = {}, tips = "", author = ""},
    ["onmermkingtridentadded_anywhere"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["onmermkingtridentremoved"] = {params = {}, tips = "", author = ""},
    ["onmermkingtridentremoved_anywhere"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["onmissother"] = {params = {}, tips = "", author = ""},
    ["onmoved"] = {params = {}, tips = "", author = ""},
    ["onnewtrophy"] = {params = {}, tips = "", author = ""},
    ["onopen"] = {params = {}, tips = "", author = ""},
    ["onopenother"] = {params = {}, tips = "", author = ""},
    ["onownerdropped"] = {params = {}, tips = "", author = ""},
    ["onownerputininventory"] = {params = {}, tips = "", author = ""},
    ["onpickup"] = {params = {}, tips = "", author = ""},
    ["onpickupitem"] = {params = {}, tips = "", author = ""},
    ["onplaced"] = {params = {}, tips = "", author = ""},
    ["onplacerhidden"] = {params = {}, tips = "", author = ""},
    ["onplayernear"] = {params = {}, tips = "", author = ""},
    ["onprefabswaped"] = {params = {}, tips = "", author = ""},
    ["onpresink"] = {params = {}, tips = "", author = ""},
    ["onputininventory"] = {params = {}, tips = "", author = ""},
    ["onreachdestination"] = {params = {}, tips = "", author = ""},
    ["onrecipescanned"] = {params = {}, tips = "", author = ""},
    ["onreflectdamage"] = {params = {}, tips = "", author = ""},
    ["onrefuseitem"] = {params = {}, tips = "", author = ""},
    ["onrefusetribute"] = {params = {}, tips = "", author = ""},
    ["onremove"] = {params = {}, tips = "", author = ""},
    ["onsatinchair"] = {params = {}, tips = "", author = ""},
    ["onscared"] = {params = {}, tips = "", author = ""},
    ["onsetskillselection_server"] = {params = {}, tips = "", author = ""},
    ["onshothit"] = {params = {}, tips = "", author = ""},
    ["onsink"] = {params = {}, tips = "", author = ""},
    ["onsinkholesfinished"] = {params = {}, tips = "", author = ""},
    ["onsinkholesstarted"] = {params = {}, tips = "", author = ""},
    ["onsisturnstatechanged"] = {params = {}, tips = "", author = ""},
    ["onskinschanged"] = {params = {}, tips = "", author = ""},
    ["onsoilmoisturestatechange"] = {params = {}, tips = "", author = ""},
    ["onstage"] = {params = {}, tips = "", author = ""},
    ["onstartconstruction"] = {params = {}, tips = "", author = ""},
    ["onstartedfire"] = {params = {}, tips = "", author = ""},
    ["onstolen"] = {params = {}, tips = "", author = ""},
    ["ontalk"] = {params = {}, tips = "", author = ""},
    ["onteach"] = {params = {}, tips = "", author = ""},
    ["onterraform"] = {params = {}, tips = "", author = ""},
    ["onthaw"] = {params = {}, tips = "", author = ""},
    ["onthronebuilt"] = {params = {}, tips = "", author = ""},
    ["onthronedestroyed"] = {params = {}, tips = "", author = ""},
    ["onthrown"] = {params = {}, tips = "", author = ""},
    ["ontrapped"] = {params = {}, tips = "", author = ""},
    ["ontuned"] = {params = {}, tips = "", author = ""},
    ["onturnoff"] = {params = {}, tips = "", author = ""},
    ["onturnon"] = {params = {}, tips = "", author = ""},
    ["onunpin"] = {params = {}, tips = "", author = ""},
    ["onvacatehome"] = {params = {}, tips = "", author = ""},
    ["onwakeup"] = {params = {}, tips = "", author = ""},
    ["onwarpback"] = {params = {}, tips = "", author = ""},
    ["onwenthome"] = {params = {}, tips = "", author = ""},
    ["onwordpredictionupdated"] = {params = {}, tips = "", author = ""},
    ["open_meter"] = {params = {}, tips = "", author = ""},
    ["opencontainer"] = {params = {}, tips = "", author = ""},
    ["openspellwheel"] = {params = {}, tips = "", author = ""},
    ["orbtaken"] = {params = {}, tips = "", author = ""},
    ["otterboaterosion_begin"] = {params = {}, tips = "", author = ""},
    ["overrideambientlighting"] = {params = {}, tips = "", author = ""},
    ["overrideambientsound"] = {params = {}, tips = "", author = ""},
    ["overridecolourcube"] = {params = {}, tips = "", author = ""},
    ["overridecolourmodifier"] = {params = {}, tips = "", author = ""},
    ["panic"] = {params = {}, tips = "", author = ""},
    ["pausehounded"] = {params = {}, tips = "", author = ""},
    ["pausequakes"] = {params = {}, tips = "", author = ""},
    ["peek"] = {params = {}, tips = "", author = ""},
    ["percentusedchange"] = {params = {}, tips = "", author = ""},
    ["perform_do_next_line"] = {params = {}, tips = "", author = ""},
    ["performaction"] = {params = {}, tips = "", author = ""},
    ["performbufferedaction"] = {params = {}, tips = "", author = ""},
    ["perishchange"] = {params = {}, tips = "", author = ""},
    ["perished"] = {params = {}, tips = "", author = ""},
    ["petbuff_dolevelchange"] = {params = {}, tips = "", author = ""},
    ["phasechange"] = {params = {}, tips = "", author = ""},
    ["phasechanged"] = {params = {}, tips = "", author = ""},
    ["phasetransition"] = {params = {}, tips = "", author = ""},
    ["picked"] = {params = {}, tips = "", author = ""},
    ["pickprop"] = {params = {}, tips = "", author = ""},
    ["picksomething"] = {params = {}, tips = "", author = ""},
    ["pickupcheat"] = {params = {}, tips = "", author = ""},
    ["pillarremoved"] = {params = {}, tips = "", author = ""},
    ["pillarvibrating"] = {params = {}, tips = "", author = ""},
    ["pillowfight_arenanotclear"] = {params = {}, tips = "", author = ""},
    ["pillowfight_arrivedatarena"] = {params = {}, tips = "", author = ""},
    ["pillowfight_deactivated"] = {params = {}, tips = "", author = ""},
    ["pillowfight_ended"] = {params = {}, tips = "", author = ""},
    ["pillowfight_fighterarrived"] = {params = {}, tips = "", author = ""},
    ["pillowfight_playhit"] = {params = {}, tips = "", author = ""},
    ["pillowfight_ringout"] = {params = {}, tips = "", author = ""},
    ["pillowfight_startgame"] = {params = {}, tips = "", author = ""},
    ["pinned"] = {params = {}, tips = "", author = ""},
    ["plantherdspawned"] = {params = {}, tips = "", author = ""},
    ["plantkilled"] = {params = {}, tips = "", author = ""},
    ["plantwintertreeseed"] = {params = {}, tips = "", author = ""},
    ["play_begun"] = {params = {}, tips = "", author = ""},
    ["play_performed"] = {params = {}, tips = "", author = ""},
    ["play_theme_music"] = {params = {}, tips = "", author = ""},
    ["play_throw_pst"] = {params = {}, tips = "", author = ""},
    ["playboatmusic"] = {params = {}, tips = "", author = ""},
    ["playboatracemusic"] = {params = {}, tips = "", author = ""},
    ["playcarnivalmusic"] = {params = {}, tips = "", author = ""},
    ["player_despawn"] = {params = {}, tips = "", author = ""},
    ["playeractivated"] = {params = {}, tips = "", author = ""},
    ["playerdeactivated"] = {params = {}, tips = "", author = ""},
    ["playerdied"] = {params = {}, tips = "", author = ""},
    ["playerentered"] = {params = {}, tips = "", author = ""},
    ["playerexited"] = {params = {}, tips = "", author = ""},
    ["playerstopturning"] = {params = {}, tips = "", author = ""},
    ["playervotechanged"] = {params = {}, tips = "", author = ""},
    ["playfarmingmusic"] = {params = {}, tips = "", author = ""},
    ["playhermitmusic"] = {params = {}, tips = "", author = ""},
    ["playpillowfightmusic"] = {params = {}, tips = "", author = ""},
    ["playpiratesmusic"] = {params = {}, tips = "", author = ""},
    ["playracemusic"] = {params = {}, tips = "", author = ""},
    ["playrideofthevalkyrie"] = {params = {}, tips = "", author = ""},
    ["playtrainingmusic"] = {params = {}, tips = "", author = ""},
    ["poisonburst"] = {params = {}, tips = "", author = ""},
    ["pollenlanded"] = {params = {}, tips = "", author = ""},
    ["pop"] = {params = {}, tips = "", author = ""},
    ["popdsp"] = {params = {}, tips = "", author = ""},
    ["popped"] = {params = {}, tips = "", author = ""},
    ["possess"] = {params = {}, tips = "", author = ""},
    ["possessedaxe"] = {params = {}, tips = "", author = ""},
    ["powerdown_wurt"] = {params = {}, tips = "", author = ""},
    ["powerup"] = {params = {}, tips = "", author = ""},
    ["powerup_wurt"] = {params = {}, tips = "", author = ""},
    ["precipitationchanged"] = {params = {}, tips = "", author = ""},
    ["preparedpop"] = {params = {}, tips = "", author = ""},
    ["propreveal"] = {params = {}, tips = "", author = ""},
    ["propsmashed"] = {params = {}, tips = "", author = ""},
    ["pushdsp"] = {params = {}, tips = "", author = ""},
    ["putoutfire"] = {params = {}, tips = "", author = ""},
    ["quagmire_notifyrecipeupdated"] = {params = {}, tips = "", author = ""},
    ["quagmire_recipeappraised"] = {params = {}, tips = "", author = ""},
    ["quagmire_recipediscovered"] = {params = {}, tips = "", author = ""},
    ["quagmire_refreshrecipbookwidget"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["quagmire_shoptab"] = {params = {}, tips = "", author = ""},
    ["quagmirehangrinessmatched"] = {params = {}, tips = "", author = ""},
    ["quagmirehangrinessrumbled"] = {params = {}, tips = "", author = ""},
    ["question"] = {params = {}, tips = "", author = ""},
    ["queuegrowantler"] = {params = {}, tips = "", author = ""},
    ["quit"] = {params = {}, tips = "", author = ""},
    ["raiseobject"] = {params = {}, tips = "", author = ""},
    ["raising_anchor"] = {params = {}, tips = "", author = ""},
    ["rampingspawner_death"] = {params = {}, tips = "", author = ""},
    ["rampingspawner_spawn"] = {params = {}, tips = "", author = ""},
    ["ratupdate"] = {params = {}, tips = "", author = ""},
    ["ready"] = {params = {}, tips = "", author = ""},
    ["reanimate"] = {params = {}, tips = "", author = ""},
    ["rechargechange"] = {params = {}, tips = "", author = ""},
    ["rechargetimechange"] = {params = {}, tips = "", author = ""},
    ["reduce_shadow_pillars_time"] = {params = {}, tips = "", author = ""},
    ["refresh"] = {params = {}, tips = "", author = ""},
    ["refreshcrafting"] = {params = {}, tips = "", author = ""},
    ["refreshhudsize"] = {params = {}, tips = "", author = ""},
    ["refreshinventory"] = {params = {}, tips = "", author = ""},
    ["refusedmount"] = {params = {}, tips = "", author = ""},
    ["refusedrider"] = {params = {}, tips = "", author = ""},
    ["refuseitem"] = {params = {}, tips = "", author = ""},
    ["reject"] = {params = {}, tips = "", author = ""},
    ["releaseclamp"] = {params = {}, tips = "", author = ""},
    ["released"] = {params = {}, tips = "", author = ""},
    ["remoteteleportreceived"] = {params = {}, tips = "", author = ""},
    ["remove_shadow_pillars"] = {params = {}, tips = "", author = ""},
    ["repair"] = {params = {}, tips = "", author = ""},
    ["repelled"] = {params = {}, tips = "", author = ""},
    ["resetruins"] = {params = {}, tips = "", author = ""},
    ["resistedgrue"] = {params = {}, tips = "", author = ""},
    ["respawnfromcorpse"] = {params = {}, tips = "", author = ""},
    ["respawnfromghost"] = {params = {}, tips = "", author = ""},
    ["rest"] = {params = {}, tips = "", author = ""},
    ["restoredfollower"] = {params = {}, tips = "", author = ""},
    ["restoredfromcollapsed"] = {params = {}, tips = "", author = ""},
    ["retract"] = {params = {}, tips = "", author = ""},
    ["rez_player"] = {params = {}, tips = "", author = ""},
    ["riderchanged"] = {params = {}, tips = "", author = ""},
    ["riderdoattackother"] = {params = {}, tips = "", author = ""},
    ["ridersleep"] = {params = {}, tips = "", author = ""},
    ["rifts_setdifficulty"] = {params = {}, tips = "", author = ""},
    ["rifts_settingsenabled"] = {params = {}, tips = "", author = ""},
    ["rifts_settingsenabled_cave"] = {params = {}, tips = "", author = ""},
    ["roar"] = {params = {}, tips = "", author = ""},
    ["rollattack"] = {params = {}, tips = "", author = ""},
    ["rooted"] = {params = {}, tips = "", author = ""},
    ["roseglassescooldownchanged"] = {params = {}, tips = "", author = ""},
    ["roseglassesvision"] = {params = {}, tips = "", author = ""},
    ["rotationdirchanged"] = {params = {}, tips = "", author = ""},
    ["rowed"] = {params = {}, tips = "", author = ""},
    ["rowing"] = {params = {}, tips = "", author = ""},
    ["ruffle"] = {params = {}, tips = "", author = ""},
    ["ruins_shadeling_looted"] = {params = {}, tips = "", author = ""},
    ["rummage"] = {params = {}, tips = "", author = ""},
    ["saddle"] = {params = {}, tips = "", author = ""},
    ["saddlechanged"] = {params = {}, tips = "", author = ""},
    ["safetospawn"] = {params = {}, tips = "", author = ""},
    ["saltchange"] = {params = {}, tips = "", author = ""},
    ["saltlick_placed"] = {params = {}, tips = "", author = ""},
    ["sandstormlevel"] = {params = {}, tips = "", author = ""},
    ["sanitydelta"] = {params = {}, tips = "", author = ""},
    ["sanitydirty"] = {params = {}, tips = "", author = ""},
    ["sanitymodechanged"] = {params = {}, tips = "", author = ""},
    ["schoolspawned"] = {params = {}, tips = "", author = ""},
    ["scrapbookopened"] = {params = {}, tips = "", author = ""},
    ["scrapbookupdated"] = {params = {}, tips = "", author = ""},
    ["scrapmonolevision"] = {params = {}, tips = "", author = ""},
    ["screech"] = {params = {}, tips = "", author = ""},
    ["screenflash"] = {params = {}, tips = "", author = ""},
    ["seamlessplayerswap"] = {params = {}, tips = "", author = ""},
    ["seamlessplayerswaptarget"] = {params = {}, tips = "", author = ""},
    ["searched"] = {params = {}, tips = "", author = ""},
    ["seasonlengthschanged"] = {params = {}, tips = "", author = ""},
    ["seasontick"] = {params = {}, tips = "", author = ""},
    ["secondary_autosaverupdate"] = {params = {}, tips = "", author = ""},
    ["secondary_clockupdate"] = {params = {}, tips = "", author = ""},
    ["secondary_seasonsupdate"] = {params = {}, tips = "", author = ""},
    ["secondary_sinkholesupdate"] = {params = {}, tips = "", author = ""},
    ["secondary_worldresetupdate"] = {params = {}, tips = "", author = ""},
    ["secondary_worldvoterenabled"] = {params = {}, tips = "", author = ""},
    ["secondary_worldvotersquelchedupdate"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["secondary_worldvoterupdate"] = {params = {}, tips = "", author = ""},
    ["seekoblivion"] = {params = {}, tips = "", author = ""},
    ["serverpauseddirty"] = {params = {}, tips = "", author = ""},
    ["set_heading"] = {params = {}, tips = "", author = ""},
    ["set_spawn_target"] = {params = {}, tips = "", author = ""},
    ["setexplosiontarget"] = {params = {}, tips = "", author = ""},
    ["setoverflow"] = {params = {}, tips = "", author = ""},
    ["setupprizes"] = {params = {}, tips = "", author = ""},
    ["sg_update_running_state"] = {params = {}, tips = "", author = ""},
    ["shadowchessroar"] = {params = {}, tips = "", author = ""},
    ["shadowmerm_spawn"] = {params = {}, tips = "", author = ""},
    ["shadowrift_opened"] = {params = {}, tips = "", author = ""},
    ["shake"] = {params = {}, tips = "", author = ""},
    ["sharkspawned"] = {params = {}, tips = "", author = ""},
    ["shaved"] = {params = {}, tips = "", author = ""},
    ["sheltered"] = {params = {}, tips = "", author = ""},
    ["show_warp_marker"] = {params = {}, tips = "", author = ""},
    ["showvotedialog"] = {params = {}, tips = "", author = ""},
    ["showworldreset"] = {params = {}, tips = "", author = ""},
    ["silentcloseinspect"] = {params = {}, tips = "", author = ""},
    ["singsong"] = {params = {}, tips = "", author = ""},
    ["sitdown"] = {params = {}, tips = "", author = ""},
    ["sittableonfire"] = {params = {}, tips = "", author = ""},
    ["sizetweener_end"] = {params = {}, tips = "", author = ""},
    ["sizetweener_start"] = {params = {}, tips = "", author = ""},
    ["skullache"] = {params = {}, tips = "", author = ""},
    ["sleepmode"] = {params = {}, tips = "", author = ""},
    ["snared"] = {params = {}, tips = "", author = ""},
    ["snowcoveredchanged"] = {params = {}, tips = "", author = ""},
    ["socket"] = {params = {}, tips = "", author = ""},
    ["soldierschanged"] = {params = {}, tips = "", author = ""},
    ["soulhop"] = {params = {}, tips = "", author = ""},
    ["souloverload"] = {params = {}, tips = "", author = ""},
    ["soultoomany"] = {params = {}, tips = "", author = ""},
    ["spawn"] = {params = {}, tips = "", author = ""},
    ["spawndevice"] = {params = {}, tips = "", author = ""},
    ["spawnedforhunt"] = {params = {}, tips = "", author = ""},
    ["spawnedfromhaunt"] = {params = {}, tips = "", author = ""},
    ["spawnlavae"] = {params = {}, tips = "", author = ""},
    ["spawnnewboatleak"] = {params = {}, tips = "", author = ""},
    ["spawnperd"] = {params = {}, tips = "", author = ""},
    ["spentfuel"] = {params = {}, tips = "", author = ""},
    ["spooked"] = {params = {}, tips = "", author = ""},
    ["spray_cloud"] = {params = {}, tips = "", author = ""},
    ["springtrap"] = {params = {}, tips = "", author = ""},
    ["stackitemdirty"] = {params = {}, tips = "", author = ""},
    ["stacksizechange"] = {params = {}, tips = "", author = ""},
    ["stacksizepreview"] = {params = {}, tips = "", author = ""},
    ["stageplaymusic"] = {params = {}, tips = "", author = ""},
    ["stalkerconsumed"] = {params = {}, tips = "", author = ""},
    ["standup"] = {params = {}, tips = "", author = ""},
    ["starsteeringreticule"] = {params = {}, tips = "", author = ""},
    ["start_abandoning"] = {params = {}, tips = "", author = ""},
    ["start_embark_movement"] = {params = {}, tips = "", author = ""},
    ["start_extending"] = {params = {}, tips = "", author = ""},
    ["start_lowering_winch"] = {params = {}, tips = "", author = ""},
    ["start_mounting"] = {params = {}, tips = "", author = ""},
    ["start_playwithplaymate"] = {params = {}, tips = "", author = ""},
    ["start_raising_winch"] = {params = {}, tips = "", author = ""},
    ["start_retracting"] = {params = {}, tips = "", author = ""},
    ["startaction"] = {params = {}, tips = "", author = ""},
    ["startchannelcast"] = {params = {}, tips = "", author = ""},
    ["startchanneling"] = {params = {}, tips = "", author = ""},
    ["startcollapse"] = {params = {}, tips = "", author = ""},
    ["startcorrosivedebuff"] = {params = {}, tips = "", author = ""},
    ["startfalling"] = {params = {}, tips = "", author = ""},
    ["startfiredamage"] = {params = {}, tips = "", author = ""},
    ["startfishinginvirtualocean"] = {params = {}, tips = "", author = ""},
    ["startflareoverlay"] = {params = {}, tips = "", author = ""},
    ["startfollowing"] = {params = {}, tips = "", author = ""},
    ["startfreezing"] = {params = {}, tips = "", author = ""},
    ["startfumedebuff"] = {params = {}, tips = "", author = ""},
    ["startghostbuildinstate"] = {params = {}, tips = "", author = ""},
    ["starthealthregen"] = {params = {}, tips = "", author = ""},
    ["startle"] = {params = {}, tips = "", author = ""},
    ["startleashing"] = {params = {}, tips = "", author = ""},
    ["startled"] = {params = {}, tips = "", author = ""},
    ["startlongaction"] = {params = {}, tips = "", author = ""},
    ["startoverheating"] = {params = {}, tips = "", author = ""},
    ["startquake"] = {params = {}, tips = "", author = ""},
    ["startsmallhealthregen"] = {params = {}, tips = "", author = ""},
    ["startspawnanim"] = {params = {}, tips = "", author = ""},
    ["startstageacting"] = {params = {}, tips = "", author = ""},
    ["startstarving"] = {params = {}, tips = "", author = ""},
    ["startstrafing"] = {params = {}, tips = "", author = ""},
    ["starttraining"] = {params = {}, tips = "", author = ""},
    ["starttravelsound"] = {params = {}, tips = "", author = ""},
    ["startwereplayer"] = {params = {}, tips = "", author = ""},
    ["startwork"] = {params = {}, tips = "", author = ""},
    ["starvedtrapsouls"] = {params = {}, tips = "", author = ""},
    ["stop_mounting"] = {params = {}, tips = "", author = ""},
    ["stop_steering_boat"] = {params = {}, tips = "", author = ""},
    ["stopaura"] = {params = {}, tips = "", author = ""},
    ["stopchannelcast"] = {params = {}, tips = "", author = ""},
    ["stopconstruction"] = {params = {}, tips = "", author = ""},
    ["stopcursechanneling"] = {params = {}, tips = "", author = ""},
    ["stopfalling"] = {params = {}, tips = "", author = ""},
    ["stopfiredamage"] = {params = {}, tips = "", author = ""},
    ["stopfiremelt"] = {params = {}, tips = "", author = ""},
    ["stopfollowing"] = {params = {}, tips = "", author = ""},
    ["stopfreezing"] = {params = {}, tips = "", author = ""},
    ["stopfurling"] = {params = {}, tips = "", author = ""},
    ["stopghostbuildinstate"] = {params = {}, tips = "", author = ""},
    ["stopleashing"] = {params = {}, tips = "", author = ""},
    ["stopliftingdumbbell"] = {params = {}, tips = "", author = ""},
    ["stopoverheating"] = {params = {}, tips = "", author = ""},
    ["stopraisinganchor"] = {params = {}, tips = "", author = ""},
    ["stopstageacting"] = {params = {}, tips = "", author = ""},
    ["stopstarving"] = {params = {}, tips = "", author = ""},
    ["stopstrafing"] = {params = {}, tips = "", author = ""},
    ["stopturning"] = {params = {}, tips = "", author = ""},
    ["stopwereplayer"] = {params = {}, tips = "", author = ""},
    ["storehassler"] = {params = {}, tips = "", author = ""},
    ["stormlevel"] = {params = {}, tips = "", author = ""},
    ["stun_finished"] = {params = {}, tips = "", author = ""},
    ["stunbomb"] = {params = {}, tips = "", author = ""},
    ["stunned"] = {params = {}, tips = "", author = ""},
    ["stunned_hit"] = {params = {}, tips = "", author = ""},
    ["submerge"] = {params = {}, tips = "", author = ""},
    ["suckedup"] = {params = {}, tips = "", author = ""},
    ["suggest_tree_target"] = {params = {}, tips = "", author = ""},
    ["summon"] = {params = {}, tips = "", author = ""},
    ["summonsdelta"] = {params = {}, tips = "", author = ""},
    ["superjumpcancelled"] = {params = {}, tips = "", author = ""},
    ["superjumpstarted"] = {params = {}, tips = "", author = ""},
    ["sway"] = {params = {}, tips = "", author = ""},
    ["tackle"] = {params = {}, tips = "", author = ""},
    ["takefuel"] = {params = {}, tips = "", author = ""},
    ["takeoversizedpicture"] = {params = {}, tips = "", author = ""},
    ["talk"] = {params = {}, tips = "", author = ""},
    ["talk_experiment"] = {params = {}, tips = "", author = ""},
    ["talkedto"] = {params = {}, tips = "", author = ""},
    ["targettracker_starttrack"] = {params = {}, tips = "", author = ""},
    ["targettracker_stoptrack"] = {params = {}, tips = "", author = ""},
    ["techlevelchange"] = {params = {}, tips = "", author = ""},
    ["techtreechange"] = {params = {}, tips = "", author = ""},
    ["teleport_to_land"] = {params = {}, tips = "", author = ""},
    ["teleport_to_sea"] = {params = {}, tips = "", author = ""},
    ["teleported"] = {params = {}, tips = "", author = ""},
    ["temperaturedelta"] = {params = {}, tips = "", author = ""},
    ["temperaturetick"] = {params = {}, tips = "", author = ""},
    ["text_changed"] = {params = {}, tips = "", author = ""},
    ["thorns"] = {params = {}, tips = "", author = ""},
    ["threatnear"] = {params = {}, tips = "", author = ""},
    ["ticoon_abandoned"] = {params = {}, tips = "", author = ""},
    ["ticoon_getattention"] = {params = {}, tips = "", author = ""},
    ["ticoon_kitcoonfound"] = {params = {}, tips = "", author = ""},
    ["tilling"] = {params = {}, tips = "", author = ""},
    ["timerdone"] = {params = {}, tips = "", author = ""},
    ["toadstoolkilled"] = {params = {}, tips = "", author = ""},
    ["toadstoollevel"] = {params = {}, tips = "", author = ""},
    ["toadstoolstatechanged"] = {params = {}, tips = "", author = ""},
    ["togglepower"] = {params = {}, tips = "", author = ""},
    ["toolbroke"] = {params = {}, tips = "", author = ""},
    ["tooltooweak"] = {params = {}, tips = "", author = ""},
    ["torchranout"] = {params = {}, tips = "", author = ""},
    ["tossitem"] = {params = {}, tips = "", author = ""},
    ["townportalactivated"] = {params = {}, tips = "", author = ""},
    ["townportaldeactivated"] = {params = {}, tips = "", author = ""},
    ["trade"] = {params = {}, tips = "", author = ""},
    ["trader_arrives"] = {params = {}, tips = "", author = ""},
    ["trader_leaves"] = {params = {}, tips = "", author = ""},
    ["transfercombattarget"] = {params = {}, tips = "", author = ""},
    ["transform"] = {params = {}, tips = "", author = ""},
    ["transform_person"] = {params = {}, tips = "", author = ""},
    ["transform_wereplayer"] = {params = {}, tips = "", author = ""},
    ["transformnormal"] = {params = {}, tips = "", author = ""},
    ["transformwere"] = {params = {}, tips = "", author = ""},
    ["transition"] = {params = {}, tips = "", author = ""},
    ["trapped"] = {params = {}, tips = "", author = ""},
    ["trigger_hedge_respawn"] = {params = {}, tips = "", author = ""},
    ["triggeredevent"] = {params = {}, tips = "", author = ""},
    ["try_jump"] = {params = {}, tips = "", author = ""},
    ["turn_on_finished"] = {params = {}, tips = "", author = ""},
    ["turnedoff"] = {params = {}, tips = "", author = ""},
    ["turnoff"] = {params = {}, tips = "", author = ""},
    ["turnoff_terrarium"] = {params = {}, tips = "", author = ""},
    ["turnon"] = {params = {}, tips = "", author = ""},
    ["twitchloginresult"] = {params = {}, tips = "", author = ""},
    ["twitchmessage"] = {params = {}, tips = "", author = ""},
    ["twitchstatusupdate"] = {params = {}, tips = "", author = ""},
    ["umbrellaranout"] = {params = {}, tips = "", author = ""},
    ["underraindomes"] = {params = {}, tips = "", author = ""},
    ["unequip"] = {params = {}, tips = "", author = ""},
    ["unequipped"] = {params = {}, tips = "", author = ""},
    ["unequipskinneditem"] = {params = {}, tips = "", author = ""},
    ["unevengrounddetected"] = {params = {}, tips = "", author = ""},
    ["unfreeze"] = {params = {}, tips = "", author = ""},
    ["unhitch"] = {params = {}, tips = "", author = ""},
    ["unhitched"] = {params = {}, tips = "", author = ""},
    ["unlinkmushroomsprout"] = {params = {}, tips = "", author = ""},
    ["unlockrecipe"] = {params = {}, tips = "", author = ""},
    ["unpausehounded"] = {params = {}, tips = "", author = ""},
    ["unpausequakes"] = {params = {}, tips = "", author = ""},
    ["unpinned"] = {params = {}, tips = "", author = ""},
    ["unregister_hudindicatable"] = {params = {}, tips = "", author = ""},
    ["unrooted"] = {params = {}, tips = "", author = ""},
    ["unshackle"] = {params = {}, tips = "", author = ""},
    ["updatelight"] = {params = {}, tips = "", author = ""},
    ["upgrademoduleowner_popallmodules"] = {
        params = {},
        tips = "",
        author = ""
    },
    ["upgrademodulesdirty"] = {params = {}, tips = "", author = ""},
    ["use_pocket_scale"] = {params = {}, tips = "", author = ""},
    ["usedtouchstone"] = {params = {}, tips = "", author = ""},
    ["usereviver"] = {params = {}, tips = "", author = ""},
    ["victory"] = {params = {}, tips = "", author = ""},
    ["votecountschanged"] = {params = {}, tips = "", author = ""},
    ["wagpunk_changelevel"] = {params = {}, tips = "", author = ""},
    ["wagpunkui_removed"] = {params = {}, tips = "", author = ""},
    ["wagpunkui_synch"] = {params = {}, tips = "", author = ""},
    ["wagpunkui_targetupdate"] = {params = {}, tips = "", author = ""},
    ["wagpunkui_worn"] = {params = {}, tips = "", author = ""},
    ["wagstaff_machine_added"] = {params = {}, tips = "", author = ""},
    ["wagstaff_machine_destroyed"] = {params = {}, tips = "", author = ""},
    ["waitfortool"] = {params = {}, tips = "", author = ""},
    ["wake_up_to_challenge"] = {params = {}, tips = "", author = ""},
    ["walkoffcreep"] = {params = {}, tips = "", author = ""},
    ["walkoncreep"] = {params = {}, tips = "", author = ""},
    ["wargshrineactivated"] = {params = {}, tips = "", author = ""},
    ["wargshrinedeactivated"] = {params = {}, tips = "", author = ""},
    ["warninglevelchanged"] = {params = {}, tips = "", author = ""},
    ["warnquake"] = {params = {}, tips = "", author = ""},
    ["weathertick"] = {params = {}, tips = "", author = ""},
    ["wereeaterchanged"] = {params = {}, tips = "", author = ""},
    ["werenessdelta"] = {params = {}, tips = "", author = ""},
    ["wetchanged"] = {params = {}, tips = "", author = ""},
    ["wetnesschange"] = {params = {}, tips = "", author = ""},
    ["win_yotb"] = {params = {}, tips = "", author = ""},
    ["winch_fully_lowered"] = {params = {}, tips = "", author = ""},
    ["winch_fully_raised"] = {params = {}, tips = "", author = ""},
    ["windchange"] = {params = {}, tips = "", author = ""},
    ["winona_batteryskillchanged"] = {params = {}, tips = "", author = ""},
    ["winona_catapultskillchanged"] = {params = {}, tips = "", author = ""},
    ["winona_spotlightskillchanged"] = {params = {}, tips = "", author = ""},
    ["wonteatfood"] = {params = {}, tips = "", author = ""},
    ["worked"] = {params = {}, tips = "", author = ""},
    ["workfinished"] = {params = {}, tips = "", author = ""},
    ["working"] = {params = {}, tips = "", author = ""},
    ["workinghit"] = {params = {}, tips = "", author = ""},
    ["workmoonbase"] = {params = {}, tips = "", author = ""},
    ["worldmapsetsize"] = {params = {}, tips = "", author = ""},
    ["worldresettick"] = {params = {}, tips = "", author = ""},
    ["worldvotertick"] = {params = {}, tips = "", author = ""},
    ["wormholetravel"] = {params = {}, tips = "", author = ""},
    ["yawn"] = {params = {}, tips = "", author = ""},
    ["yotb_advance_queue"] = {params = {}, tips = "", author = ""},
    ["yotb_contest_abort"] = {params = {}, tips = "", author = ""},
    ["yotb_contestenabled"] = {params = {}, tips = "", author = ""},
    ["yotb_contestfinished"] = {params = {}, tips = "", author = ""},
    ["yotb_conteststarted"] = {params = {}, tips = "", author = ""},
    ["yotb_learnblueprint"] = {params = {}, tips = "", author = ""},
    ["yotb_onabortcontest"] = {params = {}, tips = "", author = ""},
    ["yotb_oncontestfinshed"] = {params = {}, tips = "", author = ""},
    ["yotb_onstagebuilt"] = {params = {}, tips = "", author = ""},
    ["yotb_onstagedestroyed"] = {params = {}, tips = "", author = ""},
    ["yotb_throwprizes"] = {params = {}, tips = "", author = ""},
    ["yotbskinupdate"] = {params = {}, tips = "", author = ""},
    ["yotc_race_over"] = {params = {}, tips = "", author = ""},
    ["yotc_racebegun"] = {params = {}, tips = "", author = ""},
    ["yotc_racer_at_checkpoint"] = {params = {}, tips = "", author = ""},
    ["yotc_racer_exhausted"] = {params = {}, tips = "", author = ""},
    ["yotc_ratraceprizechange"] = {params = {}, tips = "", author = ""},
    ["yotd_ratraceprizechange"] = {params = {}, tips = "", author = ""},
    ["zoomcamera"] = {params = {}, tips = "", author = ""}
}
