return {
    ['id'] = '',
    ['API'] = '',
    ['item'] = '',
    ['nil'] = '',
    ['true'] = '',
    ['false'] = '',
    ['boolean'] = '',
    ['number'] = '',
    ['string'] = '',
    ['then'] = '',
    ['owner'] = '',
    ['inst'] = '',
    ['data'] = '',
    ['self'] = '',
    ['replica'] = '',
    ['widget'] = '',
    ['images'] = '',
    ['unique'] = '',
    ['pair'] = '',
    ['pairs'] = '',
    ['function'] = '',
        ['object'] = '',
}